// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addReadingListItemStmt, err = db.PrepareContext(ctx, addReadingListItem); err != nil {
		return nil, fmt.Errorf("error preparing query AddReadingListItem: %w", err)
	}
	if q.clearSeriesAuthorsStmt, err = db.PrepareContext(ctx, clearSeriesAuthors); err != nil {
		return nil, fmt.Errorf("error preparing query ClearSeriesAuthors: %w", err)
	}
	if q.clearSeriesLinksStmt, err = db.PrepareContext(ctx, clearSeriesLinks); err != nil {
		return nil, fmt.Errorf("error preparing query ClearSeriesLinks: %w", err)
	}
	if q.clearSeriesTagsStmt, err = db.PrepareContext(ctx, clearSeriesTags); err != nil {
		return nil, fmt.Errorf("error preparing query ClearSeriesTags: %w", err)
	}
	if q.countMihonSeriesStmt, err = db.PrepareContext(ctx, countMihonSeries); err != nil {
		return nil, fmt.Errorf("error preparing query CountMihonSeries: %w", err)
	}
	if q.countOPDSSeriesSearchStmt, err = db.PrepareContext(ctx, countOPDSSeriesSearch); err != nil {
		return nil, fmt.Errorf("error preparing query CountOPDSSeriesSearch: %w", err)
	}
	if q.createBookStmt, err = db.PrepareContext(ctx, createBook); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBook: %w", err)
	}
	if q.createLibraryStmt, err = db.PrepareContext(ctx, createLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLibrary: %w", err)
	}
	if q.createReadingListStmt, err = db.PrepareContext(ctx, createReadingList); err != nil {
		return nil, fmt.Errorf("error preparing query CreateReadingList: %w", err)
	}
	if q.createSeriesStmt, err = db.PrepareContext(ctx, createSeries); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSeries: %w", err)
	}
	if q.deleteBookStmt, err = db.PrepareContext(ctx, deleteBook); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBook: %w", err)
	}
	if q.deleteBookByPathStmt, err = db.PrepareContext(ctx, deleteBookByPath); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBookByPath: %w", err)
	}
	if q.deleteLibraryStmt, err = db.PrepareContext(ctx, deleteLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteLibrary: %w", err)
	}
	if q.deleteReadingListStmt, err = db.PrepareContext(ctx, deleteReadingList); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteReadingList: %w", err)
	}
	if q.deleteSeriesStmt, err = db.PrepareContext(ctx, deleteSeries); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSeries: %w", err)
	}
	if q.getAllAuthorsStmt, err = db.PrepareContext(ctx, getAllAuthors); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllAuthors: %w", err)
	}
	if q.getAllTagsStmt, err = db.PrepareContext(ctx, getAllTags); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllTags: %w", err)
	}
	if q.getAuthorsForSeriesStmt, err = db.PrepareContext(ctx, getAuthorsForSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthorsForSeries: %w", err)
	}
	if q.getBookStmt, err = db.PrepareContext(ctx, getBook); err != nil {
		return nil, fmt.Errorf("error preparing query GetBook: %w", err)
	}
	if q.getBookByPathStmt, err = db.PrepareContext(ctx, getBookByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetBookByPath: %w", err)
	}
	if q.getCandidateSeriesForAIStmt, err = db.PrepareContext(ctx, getCandidateSeriesForAI); err != nil {
		return nil, fmt.Errorf("error preparing query GetCandidateSeriesForAI: %w", err)
	}
	if q.getLibraryStmt, err = db.PrepareContext(ctx, getLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query GetLibrary: %w", err)
	}
	if q.getLinksForSeriesStmt, err = db.PrepareContext(ctx, getLinksForSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetLinksForSeries: %w", err)
	}
	if q.getMihonSeriesStmt, err = db.PrepareContext(ctx, getMihonSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetMihonSeries: %w", err)
	}
	if q.getNextBookInSeriesStmt, err = db.PrepareContext(ctx, getNextBookInSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetNextBookInSeries: %w", err)
	}
	if q.getReadingListStmt, err = db.PrepareContext(ctx, getReadingList); err != nil {
		return nil, fmt.Errorf("error preparing query GetReadingList: %w", err)
	}
	if q.getRecentReadSeriesStmt, err = db.PrepareContext(ctx, getRecentReadSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentReadSeries: %w", err)
	}
	if q.getSeriesStmt, err = db.PrepareContext(ctx, getSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetSeries: %w", err)
	}
	if q.getSeriesByLibraryStmt, err = db.PrepareContext(ctx, getSeriesByLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query GetSeriesByLibrary: %w", err)
	}
	if q.getSeriesWithoutCollectionStmt, err = db.PrepareContext(ctx, getSeriesWithoutCollection); err != nil {
		return nil, fmt.Errorf("error preparing query GetSeriesWithoutCollection: %w", err)
	}
	if q.getTagsForSeriesStmt, err = db.PrepareContext(ctx, getTagsForSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetTagsForSeries: %w", err)
	}
	if q.getTopReadingTagsStmt, err = db.PrepareContext(ctx, getTopReadingTags); err != nil {
		return nil, fmt.Errorf("error preparing query GetTopReadingTags: %w", err)
	}
	if q.linkSeriesAuthorStmt, err = db.PrepareContext(ctx, linkSeriesAuthor); err != nil {
		return nil, fmt.Errorf("error preparing query LinkSeriesAuthor: %w", err)
	}
	if q.linkSeriesLinkStmt, err = db.PrepareContext(ctx, linkSeriesLink); err != nil {
		return nil, fmt.Errorf("error preparing query LinkSeriesLink: %w", err)
	}
	if q.linkSeriesTagStmt, err = db.PrepareContext(ctx, linkSeriesTag); err != nil {
		return nil, fmt.Errorf("error preparing query LinkSeriesTag: %w", err)
	}
	if q.listBooksByLibraryStmt, err = db.PrepareContext(ctx, listBooksByLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query ListBooksByLibrary: %w", err)
	}
	if q.listBooksBySeriesStmt, err = db.PrepareContext(ctx, listBooksBySeries); err != nil {
		return nil, fmt.Errorf("error preparing query ListBooksBySeries: %w", err)
	}
	if q.listLibrariesStmt, err = db.PrepareContext(ctx, listLibraries); err != nil {
		return nil, fmt.Errorf("error preparing query ListLibraries: %w", err)
	}
	if q.listMihonSeriesStmt, err = db.PrepareContext(ctx, listMihonSeries); err != nil {
		return nil, fmt.Errorf("error preparing query ListMihonSeries: %w", err)
	}
	if q.listMihonSeriesByBooksStmt, err = db.PrepareContext(ctx, listMihonSeriesByBooks); err != nil {
		return nil, fmt.Errorf("error preparing query ListMihonSeriesByBooks: %w", err)
	}
	if q.listMihonSeriesByUpdatedStmt, err = db.PrepareContext(ctx, listMihonSeriesByUpdated); err != nil {
		return nil, fmt.Errorf("error preparing query ListMihonSeriesByUpdated: %w", err)
	}
	if q.listReadingListItemsStmt, err = db.PrepareContext(ctx, listReadingListItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListReadingListItems: %w", err)
	}
	if q.listReadingListsStmt, err = db.PrepareContext(ctx, listReadingLists); err != nil {
		return nil, fmt.Errorf("error preparing query ListReadingLists: %w", err)
	}
	if q.listSeriesByLibraryStmt, err = db.PrepareContext(ctx, listSeriesByLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query ListSeriesByLibrary: %w", err)
	}
	if q.removeReadingListItemStmt, err = db.PrepareContext(ctx, removeReadingListItem); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveReadingListItem: %w", err)
	}
	if q.searchOPDSSeriesStmt, err = db.PrepareContext(ctx, searchOPDSSeries); err != nil {
		return nil, fmt.Errorf("error preparing query SearchOPDSSeries: %w", err)
	}
	if q.updateBookProgressStmt, err = db.PrepareContext(ctx, updateBookProgress); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBookProgress: %w", err)
	}
	if q.updateLibraryStmt, err = db.PrepareContext(ctx, updateLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateLibrary: %w", err)
	}
	if q.updateReadingListStmt, err = db.PrepareContext(ctx, updateReadingList); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateReadingList: %w", err)
	}
	if q.updateReadingListItemSortOrderStmt, err = db.PrepareContext(ctx, updateReadingListItemSortOrder); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateReadingListItemSortOrder: %w", err)
	}
	if q.updateSeriesFavoriteStmt, err = db.PrepareContext(ctx, updateSeriesFavorite); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSeriesFavorite: %w", err)
	}
	if q.updateSeriesMetadataStmt, err = db.PrepareContext(ctx, updateSeriesMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSeriesMetadata: %w", err)
	}
	if q.updateSeriesStatisticsStmt, err = db.PrepareContext(ctx, updateSeriesStatistics); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSeriesStatistics: %w", err)
	}
	if q.upsertAuthorStmt, err = db.PrepareContext(ctx, upsertAuthor); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAuthor: %w", err)
	}
	if q.upsertBookByPathStmt, err = db.PrepareContext(ctx, upsertBookByPath); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertBookByPath: %w", err)
	}
	if q.upsertSeriesByPathStmt, err = db.PrepareContext(ctx, upsertSeriesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSeriesByPath: %w", err)
	}
	if q.upsertTagStmt, err = db.PrepareContext(ctx, upsertTag); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertTag: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addReadingListItemStmt != nil {
		if cerr := q.addReadingListItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addReadingListItemStmt: %w", cerr)
		}
	}
	if q.clearSeriesAuthorsStmt != nil {
		if cerr := q.clearSeriesAuthorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearSeriesAuthorsStmt: %w", cerr)
		}
	}
	if q.clearSeriesLinksStmt != nil {
		if cerr := q.clearSeriesLinksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearSeriesLinksStmt: %w", cerr)
		}
	}
	if q.clearSeriesTagsStmt != nil {
		if cerr := q.clearSeriesTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearSeriesTagsStmt: %w", cerr)
		}
	}
	if q.countMihonSeriesStmt != nil {
		if cerr := q.countMihonSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countMihonSeriesStmt: %w", cerr)
		}
	}
	if q.countOPDSSeriesSearchStmt != nil {
		if cerr := q.countOPDSSeriesSearchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countOPDSSeriesSearchStmt: %w", cerr)
		}
	}
	if q.createBookStmt != nil {
		if cerr := q.createBookStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBookStmt: %w", cerr)
		}
	}
	if q.createLibraryStmt != nil {
		if cerr := q.createLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLibraryStmt: %w", cerr)
		}
	}
	if q.createReadingListStmt != nil {
		if cerr := q.createReadingListStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createReadingListStmt: %w", cerr)
		}
	}
	if q.createSeriesStmt != nil {
		if cerr := q.createSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSeriesStmt: %w", cerr)
		}
	}
	if q.deleteBookStmt != nil {
		if cerr := q.deleteBookStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBookStmt: %w", cerr)
		}
	}
	if q.deleteBookByPathStmt != nil {
		if cerr := q.deleteBookByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBookByPathStmt: %w", cerr)
		}
	}
	if q.deleteLibraryStmt != nil {
		if cerr := q.deleteLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteLibraryStmt: %w", cerr)
		}
	}
	if q.deleteReadingListStmt != nil {
		if cerr := q.deleteReadingListStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteReadingListStmt: %w", cerr)
		}
	}
	if q.deleteSeriesStmt != nil {
		if cerr := q.deleteSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSeriesStmt: %w", cerr)
		}
	}
	if q.getAllAuthorsStmt != nil {
		if cerr := q.getAllAuthorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllAuthorsStmt: %w", cerr)
		}
	}
	if q.getAllTagsStmt != nil {
		if cerr := q.getAllTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllTagsStmt: %w", cerr)
		}
	}
	if q.getAuthorsForSeriesStmt != nil {
		if cerr := q.getAuthorsForSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthorsForSeriesStmt: %w", cerr)
		}
	}
	if q.getBookStmt != nil {
		if cerr := q.getBookStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookStmt: %w", cerr)
		}
	}
	if q.getBookByPathStmt != nil {
		if cerr := q.getBookByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookByPathStmt: %w", cerr)
		}
	}
	if q.getCandidateSeriesForAIStmt != nil {
		if cerr := q.getCandidateSeriesForAIStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCandidateSeriesForAIStmt: %w", cerr)
		}
	}
	if q.getLibraryStmt != nil {
		if cerr := q.getLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLibraryStmt: %w", cerr)
		}
	}
	if q.getLinksForSeriesStmt != nil {
		if cerr := q.getLinksForSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLinksForSeriesStmt: %w", cerr)
		}
	}
	if q.getMihonSeriesStmt != nil {
		if cerr := q.getMihonSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMihonSeriesStmt: %w", cerr)
		}
	}
	if q.getNextBookInSeriesStmt != nil {
		if cerr := q.getNextBookInSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNextBookInSeriesStmt: %w", cerr)
		}
	}
	if q.getReadingListStmt != nil {
		if cerr := q.getReadingListStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReadingListStmt: %w", cerr)
		}
	}
	if q.getRecentReadSeriesStmt != nil {
		if cerr := q.getRecentReadSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentReadSeriesStmt: %w", cerr)
		}
	}
	if q.getSeriesStmt != nil {
		if cerr := q.getSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSeriesStmt: %w", cerr)
		}
	}
	if q.getSeriesByLibraryStmt != nil {
		if cerr := q.getSeriesByLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSeriesByLibraryStmt: %w", cerr)
		}
	}
	if q.getSeriesWithoutCollectionStmt != nil {
		if cerr := q.getSeriesWithoutCollectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSeriesWithoutCollectionStmt: %w", cerr)
		}
	}
	if q.getTagsForSeriesStmt != nil {
		if cerr := q.getTagsForSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTagsForSeriesStmt: %w", cerr)
		}
	}
	if q.getTopReadingTagsStmt != nil {
		if cerr := q.getTopReadingTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTopReadingTagsStmt: %w", cerr)
		}
	}
	if q.linkSeriesAuthorStmt != nil {
		if cerr := q.linkSeriesAuthorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing linkSeriesAuthorStmt: %w", cerr)
		}
	}
	if q.linkSeriesLinkStmt != nil {
		if cerr := q.linkSeriesLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing linkSeriesLinkStmt: %w", cerr)
		}
	}
	if q.linkSeriesTagStmt != nil {
		if cerr := q.linkSeriesTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing linkSeriesTagStmt: %w", cerr)
		}
	}
	if q.listBooksByLibraryStmt != nil {
		if cerr := q.listBooksByLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBooksByLibraryStmt: %w", cerr)
		}
	}
	if q.listBooksBySeriesStmt != nil {
		if cerr := q.listBooksBySeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBooksBySeriesStmt: %w", cerr)
		}
	}
	if q.listLibrariesStmt != nil {
		if cerr := q.listLibrariesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLibrariesStmt: %w", cerr)
		}
	}
	if q.listMihonSeriesStmt != nil {
		if cerr := q.listMihonSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMihonSeriesStmt: %w", cerr)
		}
	}
	if q.listMihonSeriesByBooksStmt != nil {
		if cerr := q.listMihonSeriesByBooksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMihonSeriesByBooksStmt: %w", cerr)
		}
	}
	if q.listMihonSeriesByUpdatedStmt != nil {
		if cerr := q.listMihonSeriesByUpdatedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMihonSeriesByUpdatedStmt: %w", cerr)
		}
	}
	if q.listReadingListItemsStmt != nil {
		if cerr := q.listReadingListItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReadingListItemsStmt: %w", cerr)
		}
	}
	if q.listReadingListsStmt != nil {
		if cerr := q.listReadingListsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReadingListsStmt: %w", cerr)
		}
	}
	if q.listSeriesByLibraryStmt != nil {
		if cerr := q.listSeriesByLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSeriesByLibraryStmt: %w", cerr)
		}
	}
	if q.removeReadingListItemStmt != nil {
		if cerr := q.removeReadingListItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeReadingListItemStmt: %w", cerr)
		}
	}
	if q.searchOPDSSeriesStmt != nil {
		if cerr := q.searchOPDSSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchOPDSSeriesStmt: %w", cerr)
		}
	}
	if q.updateBookProgressStmt != nil {
		if cerr := q.updateBookProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBookProgressStmt: %w", cerr)
		}
	}
	if q.updateLibraryStmt != nil {
		if cerr := q.updateLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateLibraryStmt: %w", cerr)
		}
	}
	if q.updateReadingListStmt != nil {
		if cerr := q.updateReadingListStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateReadingListStmt: %w", cerr)
		}
	}
	if q.updateReadingListItemSortOrderStmt != nil {
		if cerr := q.updateReadingListItemSortOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateReadingListItemSortOrderStmt: %w", cerr)
		}
	}
	if q.updateSeriesFavoriteStmt != nil {
		if cerr := q.updateSeriesFavoriteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSeriesFavoriteStmt: %w", cerr)
		}
	}
	if q.updateSeriesMetadataStmt != nil {
		if cerr := q.updateSeriesMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSeriesMetadataStmt: %w", cerr)
		}
	}
	if q.updateSeriesStatisticsStmt != nil {
		if cerr := q.updateSeriesStatisticsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSeriesStatisticsStmt: %w", cerr)
		}
	}
	if q.upsertAuthorStmt != nil {
		if cerr := q.upsertAuthorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAuthorStmt: %w", cerr)
		}
	}
	if q.upsertBookByPathStmt != nil {
		if cerr := q.upsertBookByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertBookByPathStmt: %w", cerr)
		}
	}
	if q.upsertSeriesByPathStmt != nil {
		if cerr := q.upsertSeriesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSeriesByPathStmt: %w", cerr)
		}
	}
	if q.upsertTagStmt != nil {
		if cerr := q.upsertTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertTagStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                 DBTX
	tx                                 *sql.Tx
	addReadingListItemStmt             *sql.Stmt
	clearSeriesAuthorsStmt             *sql.Stmt
	clearSeriesLinksStmt               *sql.Stmt
	clearSeriesTagsStmt                *sql.Stmt
	countMihonSeriesStmt               *sql.Stmt
	countOPDSSeriesSearchStmt          *sql.Stmt
	createBookStmt                     *sql.Stmt
	createLibraryStmt                  *sql.Stmt
	createReadingListStmt              *sql.Stmt
	createSeriesStmt                   *sql.Stmt
	deleteBookStmt                     *sql.Stmt
	deleteBookByPathStmt               *sql.Stmt
	deleteLibraryStmt                  *sql.Stmt
	deleteReadingListStmt              *sql.Stmt
	deleteSeriesStmt                   *sql.Stmt
	getAllAuthorsStmt                  *sql.Stmt
	getAllTagsStmt                     *sql.Stmt
	getAuthorsForSeriesStmt            *sql.Stmt
	getBookStmt                        *sql.Stmt
	getBookByPathStmt                  *sql.Stmt
	getCandidateSeriesForAIStmt        *sql.Stmt
	getLibraryStmt                     *sql.Stmt
	getLinksForSeriesStmt              *sql.Stmt
	getMihonSeriesStmt                 *sql.Stmt
	getNextBookInSeriesStmt            *sql.Stmt
	getReadingListStmt                 *sql.Stmt
	getRecentReadSeriesStmt            *sql.Stmt
	getSeriesStmt                      *sql.Stmt
	getSeriesByLibraryStmt             *sql.Stmt
	getSeriesWithoutCollectionStmt     *sql.Stmt
	getTagsForSeriesStmt               *sql.Stmt
	getTopReadingTagsStmt              *sql.Stmt
	linkSeriesAuthorStmt               *sql.Stmt
	linkSeriesLinkStmt                 *sql.Stmt
	linkSeriesTagStmt                  *sql.Stmt
	listBooksByLibraryStmt             *sql.Stmt
	listBooksBySeriesStmt              *sql.Stmt
	listLibrariesStmt                  *sql.Stmt
	listMihonSeriesStmt                *sql.Stmt
	listMihonSeriesByBooksStmt         *sql.Stmt
	listMihonSeriesByUpdatedStmt       *sql.Stmt
	listReadingListItemsStmt           *sql.Stmt
	listReadingListsStmt               *sql.Stmt
	listSeriesByLibraryStmt            *sql.Stmt
	removeReadingListItemStmt          *sql.Stmt
	searchOPDSSeriesStmt               *sql.Stmt
	updateBookProgressStmt             *sql.Stmt
	updateLibraryStmt                  *sql.Stmt
	updateReadingListStmt              *sql.Stmt
	updateReadingListItemSortOrderStmt *sql.Stmt
	updateSeriesFavoriteStmt           *sql.Stmt
	updateSeriesMetadataStmt           *sql.Stmt
	updateSeriesStatisticsStmt         *sql.Stmt
	upsertAuthorStmt                   *sql.Stmt
	upsertBookByPathStmt               *sql.Stmt
	upsertSeriesByPathStmt             *sql.Stmt
	upsertTagStmt                      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		addReadingListItemStmt:             q.addReadingListItemStmt,
		clearSeriesAuthorsStmt:             q.clearSeriesAuthorsStmt,
		clearSeriesLinksStmt:               q.clearSeriesLinksStmt,
		clearSeriesTagsStmt:                q.clearSeriesTagsStmt,
		countMihonSeriesStmt:               q.countMihonSeriesStmt,
		countOPDSSeriesSearchStmt:          q.countOPDSSeriesSearchStmt,
		createBookStmt:                     q.createBookStmt,
		createLibraryStmt:                  q.createLibraryStmt,
		createReadingListStmt:              q.createReadingListStmt,
		createSeriesStmt:                   q.createSeriesStmt,
		deleteBookStmt:                     q.deleteBookStmt,
		deleteBookByPathStmt:               q.deleteBookByPathStmt,
		deleteLibraryStmt:                  q.deleteLibraryStmt,
		deleteReadingListStmt:              q.deleteReadingListStmt,
		deleteSeriesStmt:                   q.deleteSeriesStmt,
		getAllAuthorsStmt:                  q.getAllAuthorsStmt,
		getAllTagsStmt:                     q.getAllTagsStmt,
		getAuthorsForSeriesStmt:            q.getAuthorsForSeriesStmt,
		getBookStmt:                        q.getBookStmt,
		getBookByPathStmt:                  q.getBookByPathStmt,
		getCandidateSeriesForAIStmt:        q.getCandidateSeriesForAIStmt,
		getLibraryStmt:                     q.getLibraryStmt,
		getLinksForSeriesStmt:              q.getLinksForSeriesStmt,
		getMihonSeriesStmt:                 q.getMihonSeriesStmt,
		getNextBookInSeriesStmt:            q.getNextBookInSeriesStmt,
		getReadingListStmt:                 q.getReadingListStmt,
		getRecentReadSeriesStmt:            q.getRecentReadSeriesStmt,
		getSeriesStmt:                      q.getSeriesStmt,
		getSeriesByLibraryStmt:             q.getSeriesByLibraryStmt,
		getSeriesWithoutCollectionStmt:     q.getSeriesWithoutCollectionStmt,
		getTagsForSeriesStmt:               q.getTagsForSeriesStmt,
		getTopReadingTagsStmt:              q.getTopReadingTagsStmt,
		linkSeriesAuthorStmt:               q.linkSeriesAuthorStmt,
		linkSeriesLinkStmt:                 q.linkSeriesLinkStmt,
		linkSeriesTagStmt:                  q.linkSeriesTagStmt,
		listBooksByLibraryStmt:             q.listBooksByLibraryStmt,
		listBooksBySeriesStmt:              q.listBooksBySeriesStmt,
		listLibrariesStmt:                  q.listLibrariesStmt,
		listMihonSeriesStmt:                q.listMihonSeriesStmt,
		listMihonSeriesByBooksStmt:         q.listMihonSeriesByBooksStmt,
		listMihonSeriesByUpdatedStmt:       q.listMihonSeriesByUpdatedStmt,
		listReadingListItemsStmt:           q.listReadingListItemsStmt,
		listReadingListsStmt:               q.listReadingListsStmt,
		listSeriesByLibraryStmt:            q.listSeriesByLibraryStmt,
		removeReadingListItemStmt:          q.removeReadingListItemStmt,
		searchOPDSSeriesStmt:               q.searchOPDSSeriesStmt,
		updateBookProgressStmt:             q.updateBookProgressStmt,
		updateLibraryStmt:                  q.updateLibraryStmt,
		updateReadingListStmt:              q.updateReadingListStmt,
		updateReadingListItemSortOrderStmt: q.updateReadingListItemSortOrderStmt,
		updateSeriesFavoriteStmt:           q.updateSeriesFavoriteStmt,
		updateSeriesMetadataStmt:           q.updateSeriesMetadataStmt,
		updateSeriesStatisticsStmt:         q.updateSeriesStatisticsStmt,
		upsertAuthorStmt:                   q.upsertAuthorStmt,
		upsertBookByPathStmt:               q.upsertBookByPathStmt,
		upsertSeriesByPathStmt:             q.upsertSeriesByPathStmt,
		upsertTagStmt:                      q.upsertTagStmt,
	}
}
