// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createBookStmt, err = db.PrepareContext(ctx, createBook); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBook: %w", err)
	}
	if q.createBookPageStmt, err = db.PrepareContext(ctx, createBookPage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBookPage: %w", err)
	}
	if q.createLibraryStmt, err = db.PrepareContext(ctx, createLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLibrary: %w", err)
	}
	if q.createSeriesStmt, err = db.PrepareContext(ctx, createSeries); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSeries: %w", err)
	}
	if q.deleteBookByPathStmt, err = db.PrepareContext(ctx, deleteBookByPath); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBookByPath: %w", err)
	}
	if q.deletePagesByBookPathStmt, err = db.PrepareContext(ctx, deletePagesByBookPath); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePagesByBookPath: %w", err)
	}
	if q.getBookStmt, err = db.PrepareContext(ctx, getBook); err != nil {
		return nil, fmt.Errorf("error preparing query GetBook: %w", err)
	}
	if q.getBookByPathStmt, err = db.PrepareContext(ctx, getBookByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetBookByPath: %w", err)
	}
	if q.getLibraryStmt, err = db.PrepareContext(ctx, getLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query GetLibrary: %w", err)
	}
	if q.getNextBookInSeriesStmt, err = db.PrepareContext(ctx, getNextBookInSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetNextBookInSeries: %w", err)
	}
	if q.getSeriesStmt, err = db.PrepareContext(ctx, getSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetSeries: %w", err)
	}
	if q.listBookPagesStmt, err = db.PrepareContext(ctx, listBookPages); err != nil {
		return nil, fmt.Errorf("error preparing query ListBookPages: %w", err)
	}
	if q.listBooksByLibraryStmt, err = db.PrepareContext(ctx, listBooksByLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query ListBooksByLibrary: %w", err)
	}
	if q.listBooksBySeriesStmt, err = db.PrepareContext(ctx, listBooksBySeries); err != nil {
		return nil, fmt.Errorf("error preparing query ListBooksBySeries: %w", err)
	}
	if q.listLibrariesStmt, err = db.PrepareContext(ctx, listLibraries); err != nil {
		return nil, fmt.Errorf("error preparing query ListLibraries: %w", err)
	}
	if q.listSeriesByLibraryStmt, err = db.PrepareContext(ctx, listSeriesByLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query ListSeriesByLibrary: %w", err)
	}
	if q.updateBookProgressStmt, err = db.PrepareContext(ctx, updateBookProgress); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBookProgress: %w", err)
	}
	if q.upsertBookByPathStmt, err = db.PrepareContext(ctx, upsertBookByPath); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertBookByPath: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createBookStmt != nil {
		if cerr := q.createBookStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBookStmt: %w", cerr)
		}
	}
	if q.createBookPageStmt != nil {
		if cerr := q.createBookPageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBookPageStmt: %w", cerr)
		}
	}
	if q.createLibraryStmt != nil {
		if cerr := q.createLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLibraryStmt: %w", cerr)
		}
	}
	if q.createSeriesStmt != nil {
		if cerr := q.createSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSeriesStmt: %w", cerr)
		}
	}
	if q.deleteBookByPathStmt != nil {
		if cerr := q.deleteBookByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBookByPathStmt: %w", cerr)
		}
	}
	if q.deletePagesByBookPathStmt != nil {
		if cerr := q.deletePagesByBookPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePagesByBookPathStmt: %w", cerr)
		}
	}
	if q.getBookStmt != nil {
		if cerr := q.getBookStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookStmt: %w", cerr)
		}
	}
	if q.getBookByPathStmt != nil {
		if cerr := q.getBookByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookByPathStmt: %w", cerr)
		}
	}
	if q.getLibraryStmt != nil {
		if cerr := q.getLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLibraryStmt: %w", cerr)
		}
	}
	if q.getNextBookInSeriesStmt != nil {
		if cerr := q.getNextBookInSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNextBookInSeriesStmt: %w", cerr)
		}
	}
	if q.getSeriesStmt != nil {
		if cerr := q.getSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSeriesStmt: %w", cerr)
		}
	}
	if q.listBookPagesStmt != nil {
		if cerr := q.listBookPagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBookPagesStmt: %w", cerr)
		}
	}
	if q.listBooksByLibraryStmt != nil {
		if cerr := q.listBooksByLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBooksByLibraryStmt: %w", cerr)
		}
	}
	if q.listBooksBySeriesStmt != nil {
		if cerr := q.listBooksBySeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBooksBySeriesStmt: %w", cerr)
		}
	}
	if q.listLibrariesStmt != nil {
		if cerr := q.listLibrariesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLibrariesStmt: %w", cerr)
		}
	}
	if q.listSeriesByLibraryStmt != nil {
		if cerr := q.listSeriesByLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSeriesByLibraryStmt: %w", cerr)
		}
	}
	if q.updateBookProgressStmt != nil {
		if cerr := q.updateBookProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBookProgressStmt: %w", cerr)
		}
	}
	if q.upsertBookByPathStmt != nil {
		if cerr := q.upsertBookByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertBookByPathStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	createBookStmt            *sql.Stmt
	createBookPageStmt        *sql.Stmt
	createLibraryStmt         *sql.Stmt
	createSeriesStmt          *sql.Stmt
	deleteBookByPathStmt      *sql.Stmt
	deletePagesByBookPathStmt *sql.Stmt
	getBookStmt               *sql.Stmt
	getBookByPathStmt         *sql.Stmt
	getLibraryStmt            *sql.Stmt
	getNextBookInSeriesStmt   *sql.Stmt
	getSeriesStmt             *sql.Stmt
	listBookPagesStmt         *sql.Stmt
	listBooksByLibraryStmt    *sql.Stmt
	listBooksBySeriesStmt     *sql.Stmt
	listLibrariesStmt         *sql.Stmt
	listSeriesByLibraryStmt   *sql.Stmt
	updateBookProgressStmt    *sql.Stmt
	upsertBookByPathStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		createBookStmt:            q.createBookStmt,
		createBookPageStmt:        q.createBookPageStmt,
		createLibraryStmt:         q.createLibraryStmt,
		createSeriesStmt:          q.createSeriesStmt,
		deleteBookByPathStmt:      q.deleteBookByPathStmt,
		deletePagesByBookPathStmt: q.deletePagesByBookPathStmt,
		getBookStmt:               q.getBookStmt,
		getBookByPathStmt:         q.getBookByPathStmt,
		getLibraryStmt:            q.getLibraryStmt,
		getNextBookInSeriesStmt:   q.getNextBookInSeriesStmt,
		getSeriesStmt:             q.getSeriesStmt,
		listBookPagesStmt:         q.listBookPagesStmt,
		listBooksByLibraryStmt:    q.listBooksByLibraryStmt,
		listBooksBySeriesStmt:     q.listBooksBySeriesStmt,
		listLibrariesStmt:         q.listLibrariesStmt,
		listSeriesByLibraryStmt:   q.listSeriesByLibraryStmt,
		updateBookProgressStmt:    q.updateBookProgressStmt,
		upsertBookByPathStmt:      q.upsertBookByPathStmt,
	}
}
