// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.clearSeriesAuthorsStmt, err = db.PrepareContext(ctx, clearSeriesAuthors); err != nil {
		return nil, fmt.Errorf("error preparing query ClearSeriesAuthors: %w", err)
	}
	if q.clearSeriesTagsStmt, err = db.PrepareContext(ctx, clearSeriesTags); err != nil {
		return nil, fmt.Errorf("error preparing query ClearSeriesTags: %w", err)
	}
	if q.createBookStmt, err = db.PrepareContext(ctx, createBook); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBook: %w", err)
	}
	if q.createBookPageStmt, err = db.PrepareContext(ctx, createBookPage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBookPage: %w", err)
	}
	if q.createLibraryStmt, err = db.PrepareContext(ctx, createLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLibrary: %w", err)
	}
	if q.createSeriesStmt, err = db.PrepareContext(ctx, createSeries); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSeries: %w", err)
	}
	if q.deleteBookByPathStmt, err = db.PrepareContext(ctx, deleteBookByPath); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBookByPath: %w", err)
	}
	if q.deleteLibraryStmt, err = db.PrepareContext(ctx, deleteLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteLibrary: %w", err)
	}
	if q.deletePagesByBookPathStmt, err = db.PrepareContext(ctx, deletePagesByBookPath); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePagesByBookPath: %w", err)
	}
	if q.getAllAuthorsStmt, err = db.PrepareContext(ctx, getAllAuthors); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllAuthors: %w", err)
	}
	if q.getAllTagsStmt, err = db.PrepareContext(ctx, getAllTags); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllTags: %w", err)
	}
	if q.getAuthorsForSeriesStmt, err = db.PrepareContext(ctx, getAuthorsForSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthorsForSeries: %w", err)
	}
	if q.getBookStmt, err = db.PrepareContext(ctx, getBook); err != nil {
		return nil, fmt.Errorf("error preparing query GetBook: %w", err)
	}
	if q.getBookByPathStmt, err = db.PrepareContext(ctx, getBookByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetBookByPath: %w", err)
	}
	if q.getLibraryStmt, err = db.PrepareContext(ctx, getLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query GetLibrary: %w", err)
	}
	if q.getNextBookInSeriesStmt, err = db.PrepareContext(ctx, getNextBookInSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetNextBookInSeries: %w", err)
	}
	if q.getSeriesStmt, err = db.PrepareContext(ctx, getSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetSeries: %w", err)
	}
	if q.getSeriesByLibraryStmt, err = db.PrepareContext(ctx, getSeriesByLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query GetSeriesByLibrary: %w", err)
	}
	if q.getTagsForSeriesStmt, err = db.PrepareContext(ctx, getTagsForSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetTagsForSeries: %w", err)
	}
	if q.linkSeriesAuthorStmt, err = db.PrepareContext(ctx, linkSeriesAuthor); err != nil {
		return nil, fmt.Errorf("error preparing query LinkSeriesAuthor: %w", err)
	}
	if q.linkSeriesTagStmt, err = db.PrepareContext(ctx, linkSeriesTag); err != nil {
		return nil, fmt.Errorf("error preparing query LinkSeriesTag: %w", err)
	}
	if q.listBookPagesStmt, err = db.PrepareContext(ctx, listBookPages); err != nil {
		return nil, fmt.Errorf("error preparing query ListBookPages: %w", err)
	}
	if q.listBooksByLibraryStmt, err = db.PrepareContext(ctx, listBooksByLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query ListBooksByLibrary: %w", err)
	}
	if q.listBooksBySeriesStmt, err = db.PrepareContext(ctx, listBooksBySeries); err != nil {
		return nil, fmt.Errorf("error preparing query ListBooksBySeries: %w", err)
	}
	if q.listLibrariesStmt, err = db.PrepareContext(ctx, listLibraries); err != nil {
		return nil, fmt.Errorf("error preparing query ListLibraries: %w", err)
	}
	if q.listSeriesByLibraryStmt, err = db.PrepareContext(ctx, listSeriesByLibrary); err != nil {
		return nil, fmt.Errorf("error preparing query ListSeriesByLibrary: %w", err)
	}
	if q.updateBookProgressStmt, err = db.PrepareContext(ctx, updateBookProgress); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBookProgress: %w", err)
	}
	if q.updateSeriesMetadataStmt, err = db.PrepareContext(ctx, updateSeriesMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSeriesMetadata: %w", err)
	}
	if q.upsertAuthorStmt, err = db.PrepareContext(ctx, upsertAuthor); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAuthor: %w", err)
	}
	if q.upsertBookByPathStmt, err = db.PrepareContext(ctx, upsertBookByPath); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertBookByPath: %w", err)
	}
	if q.upsertSeriesByPathStmt, err = db.PrepareContext(ctx, upsertSeriesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSeriesByPath: %w", err)
	}
	if q.upsertTagStmt, err = db.PrepareContext(ctx, upsertTag); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertTag: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.clearSeriesAuthorsStmt != nil {
		if cerr := q.clearSeriesAuthorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearSeriesAuthorsStmt: %w", cerr)
		}
	}
	if q.clearSeriesTagsStmt != nil {
		if cerr := q.clearSeriesTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearSeriesTagsStmt: %w", cerr)
		}
	}
	if q.createBookStmt != nil {
		if cerr := q.createBookStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBookStmt: %w", cerr)
		}
	}
	if q.createBookPageStmt != nil {
		if cerr := q.createBookPageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBookPageStmt: %w", cerr)
		}
	}
	if q.createLibraryStmt != nil {
		if cerr := q.createLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLibraryStmt: %w", cerr)
		}
	}
	if q.createSeriesStmt != nil {
		if cerr := q.createSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSeriesStmt: %w", cerr)
		}
	}
	if q.deleteBookByPathStmt != nil {
		if cerr := q.deleteBookByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBookByPathStmt: %w", cerr)
		}
	}
	if q.deleteLibraryStmt != nil {
		if cerr := q.deleteLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteLibraryStmt: %w", cerr)
		}
	}
	if q.deletePagesByBookPathStmt != nil {
		if cerr := q.deletePagesByBookPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePagesByBookPathStmt: %w", cerr)
		}
	}
	if q.getAllAuthorsStmt != nil {
		if cerr := q.getAllAuthorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllAuthorsStmt: %w", cerr)
		}
	}
	if q.getAllTagsStmt != nil {
		if cerr := q.getAllTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllTagsStmt: %w", cerr)
		}
	}
	if q.getAuthorsForSeriesStmt != nil {
		if cerr := q.getAuthorsForSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthorsForSeriesStmt: %w", cerr)
		}
	}
	if q.getBookStmt != nil {
		if cerr := q.getBookStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookStmt: %w", cerr)
		}
	}
	if q.getBookByPathStmt != nil {
		if cerr := q.getBookByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookByPathStmt: %w", cerr)
		}
	}
	if q.getLibraryStmt != nil {
		if cerr := q.getLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLibraryStmt: %w", cerr)
		}
	}
	if q.getNextBookInSeriesStmt != nil {
		if cerr := q.getNextBookInSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNextBookInSeriesStmt: %w", cerr)
		}
	}
	if q.getSeriesStmt != nil {
		if cerr := q.getSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSeriesStmt: %w", cerr)
		}
	}
	if q.getSeriesByLibraryStmt != nil {
		if cerr := q.getSeriesByLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSeriesByLibraryStmt: %w", cerr)
		}
	}
	if q.getTagsForSeriesStmt != nil {
		if cerr := q.getTagsForSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTagsForSeriesStmt: %w", cerr)
		}
	}
	if q.linkSeriesAuthorStmt != nil {
		if cerr := q.linkSeriesAuthorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing linkSeriesAuthorStmt: %w", cerr)
		}
	}
	if q.linkSeriesTagStmt != nil {
		if cerr := q.linkSeriesTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing linkSeriesTagStmt: %w", cerr)
		}
	}
	if q.listBookPagesStmt != nil {
		if cerr := q.listBookPagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBookPagesStmt: %w", cerr)
		}
	}
	if q.listBooksByLibraryStmt != nil {
		if cerr := q.listBooksByLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBooksByLibraryStmt: %w", cerr)
		}
	}
	if q.listBooksBySeriesStmt != nil {
		if cerr := q.listBooksBySeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBooksBySeriesStmt: %w", cerr)
		}
	}
	if q.listLibrariesStmt != nil {
		if cerr := q.listLibrariesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLibrariesStmt: %w", cerr)
		}
	}
	if q.listSeriesByLibraryStmt != nil {
		if cerr := q.listSeriesByLibraryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSeriesByLibraryStmt: %w", cerr)
		}
	}
	if q.updateBookProgressStmt != nil {
		if cerr := q.updateBookProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBookProgressStmt: %w", cerr)
		}
	}
	if q.updateSeriesMetadataStmt != nil {
		if cerr := q.updateSeriesMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSeriesMetadataStmt: %w", cerr)
		}
	}
	if q.upsertAuthorStmt != nil {
		if cerr := q.upsertAuthorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAuthorStmt: %w", cerr)
		}
	}
	if q.upsertBookByPathStmt != nil {
		if cerr := q.upsertBookByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertBookByPathStmt: %w", cerr)
		}
	}
	if q.upsertSeriesByPathStmt != nil {
		if cerr := q.upsertSeriesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSeriesByPathStmt: %w", cerr)
		}
	}
	if q.upsertTagStmt != nil {
		if cerr := q.upsertTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertTagStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	clearSeriesAuthorsStmt    *sql.Stmt
	clearSeriesTagsStmt       *sql.Stmt
	createBookStmt            *sql.Stmt
	createBookPageStmt        *sql.Stmt
	createLibraryStmt         *sql.Stmt
	createSeriesStmt          *sql.Stmt
	deleteBookByPathStmt      *sql.Stmt
	deleteLibraryStmt         *sql.Stmt
	deletePagesByBookPathStmt *sql.Stmt
	getAllAuthorsStmt         *sql.Stmt
	getAllTagsStmt            *sql.Stmt
	getAuthorsForSeriesStmt   *sql.Stmt
	getBookStmt               *sql.Stmt
	getBookByPathStmt         *sql.Stmt
	getLibraryStmt            *sql.Stmt
	getNextBookInSeriesStmt   *sql.Stmt
	getSeriesStmt             *sql.Stmt
	getSeriesByLibraryStmt    *sql.Stmt
	getTagsForSeriesStmt      *sql.Stmt
	linkSeriesAuthorStmt      *sql.Stmt
	linkSeriesTagStmt         *sql.Stmt
	listBookPagesStmt         *sql.Stmt
	listBooksByLibraryStmt    *sql.Stmt
	listBooksBySeriesStmt     *sql.Stmt
	listLibrariesStmt         *sql.Stmt
	listSeriesByLibraryStmt   *sql.Stmt
	updateBookProgressStmt    *sql.Stmt
	updateSeriesMetadataStmt  *sql.Stmt
	upsertAuthorStmt          *sql.Stmt
	upsertBookByPathStmt      *sql.Stmt
	upsertSeriesByPathStmt    *sql.Stmt
	upsertTagStmt             *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		clearSeriesAuthorsStmt:    q.clearSeriesAuthorsStmt,
		clearSeriesTagsStmt:       q.clearSeriesTagsStmt,
		createBookStmt:            q.createBookStmt,
		createBookPageStmt:        q.createBookPageStmt,
		createLibraryStmt:         q.createLibraryStmt,
		createSeriesStmt:          q.createSeriesStmt,
		deleteBookByPathStmt:      q.deleteBookByPathStmt,
		deleteLibraryStmt:         q.deleteLibraryStmt,
		deletePagesByBookPathStmt: q.deletePagesByBookPathStmt,
		getAllAuthorsStmt:         q.getAllAuthorsStmt,
		getAllTagsStmt:            q.getAllTagsStmt,
		getAuthorsForSeriesStmt:   q.getAuthorsForSeriesStmt,
		getBookStmt:               q.getBookStmt,
		getBookByPathStmt:         q.getBookByPathStmt,
		getLibraryStmt:            q.getLibraryStmt,
		getNextBookInSeriesStmt:   q.getNextBookInSeriesStmt,
		getSeriesStmt:             q.getSeriesStmt,
		getSeriesByLibraryStmt:    q.getSeriesByLibraryStmt,
		getTagsForSeriesStmt:      q.getTagsForSeriesStmt,
		linkSeriesAuthorStmt:      q.linkSeriesAuthorStmt,
		linkSeriesTagStmt:         q.linkSeriesTagStmt,
		listBookPagesStmt:         q.listBookPagesStmt,
		listBooksByLibraryStmt:    q.listBooksByLibraryStmt,
		listBooksBySeriesStmt:     q.listBooksBySeriesStmt,
		listLibrariesStmt:         q.listLibrariesStmt,
		listSeriesByLibraryStmt:   q.listSeriesByLibraryStmt,
		updateBookProgressStmt:    q.updateBookProgressStmt,
		updateSeriesMetadataStmt:  q.updateSeriesMetadataStmt,
		upsertAuthorStmt:          q.upsertAuthorStmt,
		upsertBookByPathStmt:      q.upsertBookByPathStmt,
		upsertSeriesByPathStmt:    q.upsertSeriesByPathStmt,
		upsertTagStmt:             q.upsertTagStmt,
	}
}
