// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Author struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Role      string       `json:"role"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Book struct {
	ID             int64           `json:"id"`
	SeriesID       int64           `json:"series_id"`
	LibraryID      int64           `json:"library_id"`
	Name           string          `json:"name"`
	Path           string          `json:"path"`
	Size           int64           `json:"size"`
	FileModifiedAt time.Time       `json:"file_modified_at"`
	Volume         string          `json:"volume"`
	Title          sql.NullString  `json:"title"`
	Summary        sql.NullString  `json:"summary"`
	Number         sql.NullString  `json:"number"`
	SortNumber     sql.NullFloat64 `json:"sort_number"`
	PageCount      int64           `json:"page_count"`
	CoverPath      sql.NullString  `json:"cover_path"`
	LastReadPage   sql.NullInt64   `json:"last_read_page"`
	LastReadAt     sql.NullTime    `json:"last_read_at"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type Library struct {
	ID           int64        `json:"id"`
	Name         string       `json:"name"`
	Path         string       `json:"path"`
	AutoScan     bool         `json:"auto_scan"`
	ScanInterval int64        `json:"scan_interval"`
	ScanFormats  string       `json:"scan_formats"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type Series struct {
	ID           int64           `json:"id"`
	LibraryID    int64           `json:"library_id"`
	Name         string          `json:"name"`
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	Path         string          `json:"path"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	IsFavorite   bool            `json:"is_favorite"`
}

type SeriesAuthor struct {
	SeriesID int64 `json:"series_id"`
	AuthorID int64 `json:"author_id"`
}

type SeriesLink struct {
	ID        int64        `json:"id"`
	SeriesID  int64        `json:"series_id"`
	Name      string       `json:"name"`
	Url       string       `json:"url"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type SeriesTag struct {
	SeriesID int64 `json:"series_id"`
	TagID    int64 `json:"tag_id"`
}

type Tag struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}
