// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type AiGroupingReview struct {
	ID              int64        `json:"id"`
	LibraryID       int64        `json:"library_id"`
	Provider        string       `json:"provider"`
	Status          string       `json:"status"`
	Summary         string       `json:"summary"`
	RawPayload      string       `json:"raw_payload"`
	CandidateCount  int64        `json:"candidate_count"`
	CollectionCount int64        `json:"collection_count"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	AppliedAt       sql.NullTime `json:"applied_at"`
	RejectedAt      sql.NullTime `json:"rejected_at"`
}

type AiGroupingReviewCollection struct {
	ID                  int64         `json:"id"`
	ReviewID            int64         `json:"review_id"`
	Name                string        `json:"name"`
	Description         string        `json:"description"`
	SeriesIds           string        `json:"series_ids"`
	SeriesCount         int64         `json:"series_count"`
	Status              string        `json:"status"`
	CreatedCollectionID sql.NullInt64 `json:"created_collection_id"`
	CreatedAt           time.Time     `json:"created_at"`
	UpdatedAt           time.Time     `json:"updated_at"`
}

type Author struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Role      string       `json:"role"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Book struct {
	ID                   int64           `json:"id"`
	SeriesID             int64           `json:"series_id"`
	LibraryID            int64           `json:"library_id"`
	Name                 string          `json:"name"`
	Path                 string          `json:"path"`
	Size                 int64           `json:"size"`
	FileModifiedAt       time.Time       `json:"file_modified_at"`
	Volume               string          `json:"volume"`
	Title                sql.NullString  `json:"title"`
	Summary              sql.NullString  `json:"summary"`
	Number               sql.NullString  `json:"number"`
	SortNumber           sql.NullFloat64 `json:"sort_number"`
	PageCount            int64           `json:"page_count"`
	CoverPath            sql.NullString  `json:"cover_path"`
	LastReadPage         sql.NullInt64   `json:"last_read_page"`
	LastReadAt           sql.NullTime    `json:"last_read_at"`
	FileHash             sql.NullString  `json:"file_hash"`
	QuickHash            sql.NullString  `json:"quick_hash"`
	PathFingerprint      sql.NullString  `json:"path_fingerprint"`
	PathFingerprintNoExt sql.NullString  `json:"path_fingerprint_no_ext"`
	FilenameFingerprint  sql.NullString  `json:"filename_fingerprint"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

type Collection struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	CoverUrl       sql.NullString `json:"cover_url"`
	SortOrder      int64          `json:"sort_order"`
	SourceType     string         `json:"source_type"`
	SourceReviewID sql.NullInt64  `json:"source_review_id"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type CollectionSeries struct {
	CollectionID int64        `json:"collection_id"`
	SeriesID     int64        `json:"series_id"`
	SortOrder    int64        `json:"sort_order"`
	AddedAt      sql.NullTime `json:"added_at"`
}

type KoreaderAccount struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	SyncKey   string    `json:"sync_key"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type KoreaderProgress struct {
	ID         int64         `json:"id"`
	Username   string        `json:"username"`
	Document   string        `json:"document"`
	Progress   string        `json:"progress"`
	Percentage float64       `json:"percentage"`
	Device     string        `json:"device"`
	DeviceID   string        `json:"device_id"`
	BookID     sql.NullInt64 `json:"book_id"`
	MatchedBy  string        `json:"matched_by"`
	Timestamp  int64         `json:"timestamp"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
	RawPayload string        `json:"raw_payload"`
}

type KoreaderSetting struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type KoreaderSyncEvent struct {
	ID        int64         `json:"id"`
	Direction string        `json:"direction"`
	Username  string        `json:"username"`
	Document  string        `json:"document"`
	BookID    sql.NullInt64 `json:"book_id"`
	Status    string        `json:"status"`
	Message   string        `json:"message"`
	CreatedAt time.Time     `json:"created_at"`
}

type Library struct {
	ID                  int64        `json:"id"`
	Name                string       `json:"name"`
	Path                string       `json:"path"`
	ScanMode            string       `json:"scan_mode"`
	KoreaderSyncEnabled bool         `json:"koreader_sync_enabled"`
	ScanInterval        int64        `json:"scan_interval"`
	ScanFormats         string       `json:"scan_formats"`
	CreatedAt           sql.NullTime `json:"created_at"`
}

type MetadataReview struct {
	ID          int64        `json:"id"`
	SeriesID    int64        `json:"series_id"`
	Provider    string       `json:"provider"`
	SourceUrl   string       `json:"source_url"`
	SourceID    int64        `json:"source_id"`
	SourceQuery string       `json:"source_query"`
	Summary     string       `json:"summary"`
	Confidence  float64      `json:"confidence"`
	Status      string       `json:"status"`
	RawPayload  string       `json:"raw_payload"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	AppliedAt   sql.NullTime `json:"applied_at"`
	RejectedAt  sql.NullTime `json:"rejected_at"`
}

type MetadataReviewField struct {
	ID            int64     `json:"id"`
	ReviewID      int64     `json:"review_id"`
	FieldName     string    `json:"field_name"`
	CurrentValue  string    `json:"current_value"`
	ProposedValue string    `json:"proposed_value"`
	Confidence    float64   `json:"confidence"`
	Source        string    `json:"source"`
	SourceUrl     string    `json:"source_url"`
	Locked        bool      `json:"locked"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ReadingActivity struct {
	ID        int64        `json:"id"`
	BookID    int64        `json:"book_id"`
	Date      string       `json:"date"`
	PagesRead int64        `json:"pages_read"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type ReadingBookmark struct {
	ID        int64     `json:"id"`
	BookID    int64     `json:"book_id"`
	Page      int64     `json:"page"`
	Note      string    `json:"note"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ReadingList struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	SortOrder   int64     `json:"sort_order"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ReadingListItem struct {
	ID            int64     `json:"id"`
	ReadingListID int64     `json:"reading_list_id"`
	SeriesID      int64     `json:"series_id"`
	SortOrder     int64     `json:"sort_order"`
	Note          string    `json:"note"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Series struct {
	ID           int64           `json:"id"`
	LibraryID    int64           `json:"library_id"`
	Name         string          `json:"name"`
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	NameInitial  string          `json:"name_initial"`
	Path         string          `json:"path"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	IsFavorite   bool            `json:"is_favorite"`
	VolumeCount  int64           `json:"volume_count"`
	BookCount    int64           `json:"book_count"`
	TotalPages   int64           `json:"total_pages"`
}

type SeriesAuthor struct {
	SeriesID int64 `json:"series_id"`
	AuthorID int64 `json:"author_id"`
}

type SeriesLink struct {
	ID        int64        `json:"id"`
	SeriesID  int64        `json:"series_id"`
	Name      string       `json:"name"`
	Url       string       `json:"url"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type SeriesMetadataProvenance struct {
	SeriesID   int64         `json:"series_id"`
	FieldName  string        `json:"field_name"`
	Value      string        `json:"value"`
	Source     string        `json:"source"`
	SourceUrl  string        `json:"source_url"`
	Confidence float64       `json:"confidence"`
	ReviewID   sql.NullInt64 `json:"review_id"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type SeriesRelation struct {
	ID             int64        `json:"id"`
	SourceSeriesID int64        `json:"source_series_id"`
	TargetSeriesID int64        `json:"target_series_id"`
	RelationType   string       `json:"relation_type"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type SeriesTag struct {
	SeriesID int64 `json:"series_id"`
	TagID    int64 `json:"tag_id"`
}

type SmartFilter struct {
	ID              int64           `json:"id"`
	LibraryID       int64           `json:"library_id"`
	Name            string          `json:"name"`
	ActiveTag       sql.NullString  `json:"active_tag"`
	ActiveAuthor    sql.NullString  `json:"active_author"`
	ActiveStatus    sql.NullString  `json:"active_status"`
	ActiveLetter    sql.NullString  `json:"active_letter"`
	ReadState       sql.NullString  `json:"read_state"`
	MinRating       sql.NullFloat64 `json:"min_rating"`
	MaxRating       sql.NullFloat64 `json:"max_rating"`
	MinProgress     sql.NullFloat64 `json:"min_progress"`
	MaxProgress     sql.NullFloat64 `json:"max_progress"`
	AddedWithinDays sql.NullInt64   `json:"added_within_days"`
	SortByField     string          `json:"sort_by_field"`
	SortDir         string          `json:"sort_dir"`
	PageSize        int64           `json:"page_size"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type Tag struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Task struct {
	Key        string        `json:"key"`
	Type       string        `json:"type"`
	Scope      string        `json:"scope"`
	ScopeID    sql.NullInt64 `json:"scope_id"`
	ScopeName  string        `json:"scope_name"`
	Status     string        `json:"status"`
	Message    string        `json:"message"`
	Error      string        `json:"error"`
	Current    int64         `json:"current"`
	Total      int64         `json:"total"`
	CanCancel  bool          `json:"can_cancel"`
	Retryable  bool          `json:"retryable"`
	Params     string        `json:"params"`
	StartedAt  time.Time     `json:"started_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
	FinishedAt sql.NullTime  `json:"finished_at"`
	Sequence   int64         `json:"sequence"`
}
