// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const clearSeriesAuthors = `-- name: ClearSeriesAuthors :exec
DELETE FROM series_authors WHERE series_id = ?
`

func (q *Queries) ClearSeriesAuthors(ctx context.Context, seriesID int64) error {
	_, err := q.exec(ctx, q.clearSeriesAuthorsStmt, clearSeriesAuthors, seriesID)
	return err
}

const clearSeriesLinks = `-- name: ClearSeriesLinks :exec
DELETE FROM series_links WHERE series_id = ?
`

func (q *Queries) ClearSeriesLinks(ctx context.Context, seriesID int64) error {
	_, err := q.exec(ctx, q.clearSeriesLinksStmt, clearSeriesLinks, seriesID)
	return err
}

const clearSeriesTags = `-- name: ClearSeriesTags :exec
DELETE FROM series_tags WHERE series_id = ?
`

func (q *Queries) ClearSeriesTags(ctx context.Context, seriesID int64) error {
	_, err := q.exec(ctx, q.clearSeriesTagsStmt, clearSeriesTags, seriesID)
	return err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    series_id, library_id, name, path, size, file_modified_at, 
    volume, title, summary, number, sort_number, page_count, cover_path
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, series_id, library_id, name, path, size, file_modified_at, volume, title, summary, number, sort_number, page_count, cover_path, last_read_page, last_read_at, created_at, updated_at
`

type CreateBookParams struct {
	SeriesID       int64           `json:"series_id"`
	LibraryID      int64           `json:"library_id"`
	Name           string          `json:"name"`
	Path           string          `json:"path"`
	Size           int64           `json:"size"`
	FileModifiedAt time.Time       `json:"file_modified_at"`
	Volume         string          `json:"volume"`
	Title          sql.NullString  `json:"title"`
	Summary        sql.NullString  `json:"summary"`
	Number         sql.NullString  `json:"number"`
	SortNumber     sql.NullFloat64 `json:"sort_number"`
	PageCount      int64           `json:"page_count"`
	CoverPath      sql.NullString  `json:"cover_path"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.queryRow(ctx, q.createBookStmt, createBook,
		arg.SeriesID,
		arg.LibraryID,
		arg.Name,
		arg.Path,
		arg.Size,
		arg.FileModifiedAt,
		arg.Volume,
		arg.Title,
		arg.Summary,
		arg.Number,
		arg.SortNumber,
		arg.PageCount,
		arg.CoverPath,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Volume,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CoverPath,
		&i.LastReadPage,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO libraries (name, path, auto_scan, scan_interval, scan_formats)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, path, auto_scan, scan_interval, scan_formats, created_at
`

type CreateLibraryParams struct {
	Name         string `json:"name"`
	Path         string `json:"path"`
	AutoScan     bool   `json:"auto_scan"`
	ScanInterval int64  `json:"scan_interval"`
	ScanFormats  string `json:"scan_formats"`
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.queryRow(ctx, q.createLibraryStmt, createLibrary,
		arg.Name,
		arg.Path,
		arg.AutoScan,
		arg.ScanInterval,
		arg.ScanFormats,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.AutoScan,
		&i.ScanInterval,
		&i.ScanFormats,
		&i.CreatedAt,
	)
	return i, err
}

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (
    library_id, name, path, title, summary, publisher, status, rating, language, locked_fields
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, library_id, name, title, summary, publisher, status, rating, language, locked_fields, path, created_at, updated_at, is_favorite
`

type CreateSeriesParams struct {
	LibraryID    int64           `json:"library_id"`
	Name         string          `json:"name"`
	Path         string          `json:"path"`
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.queryRow(ctx, q.createSeriesStmt, createSeries,
		arg.LibraryID,
		arg.Name,
		arg.Path,
		arg.Title,
		arg.Summary,
		arg.Publisher,
		arg.Status,
		arg.Rating,
		arg.Language,
		arg.LockedFields,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Title,
		&i.Summary,
		&i.Publisher,
		&i.Status,
		&i.Rating,
		&i.Language,
		&i.LockedFields,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsFavorite,
	)
	return i, err
}

const deleteBookByPath = `-- name: DeleteBookByPath :exec
DELETE FROM books WHERE path = ?
`

func (q *Queries) DeleteBookByPath(ctx context.Context, path string) error {
	_, err := q.exec(ctx, q.deleteBookByPathStmt, deleteBookByPath, path)
	return err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE FROM libraries WHERE id = ?
`

func (q *Queries) DeleteLibrary(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteLibraryStmt, deleteLibrary, id)
	return err
}

const getAllAuthors = `-- name: GetAllAuthors :many
SELECT id, name, role, created_at FROM authors ORDER BY name
`

func (q *Queries) GetAllAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.query(ctx, q.getAllAuthorsStmt, getAllAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTags = `-- name: GetAllTags :many
SELECT id, name, created_at FROM tags ORDER BY name
`

func (q *Queries) GetAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.query(ctx, q.getAllTagsStmt, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorsForSeries = `-- name: GetAuthorsForSeries :many
SELECT a.id, a.name, a.role, a.created_at FROM authors a
JOIN series_authors sa ON a.id = sa.author_id
WHERE sa.series_id = ? ORDER BY a.role, a.name
`

func (q *Queries) GetAuthorsForSeries(ctx context.Context, seriesID int64) ([]Author, error) {
	rows, err := q.query(ctx, q.getAuthorsForSeriesStmt, getAuthorsForSeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBook = `-- name: GetBook :one
SELECT id, series_id, library_id, name, path, size, file_modified_at, volume, title, summary, number, sort_number, page_count, cover_path, last_read_page, last_read_at, created_at, updated_at FROM books WHERE id = ? LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.queryRow(ctx, q.getBookStmt, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Volume,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CoverPath,
		&i.LastReadPage,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookByPath = `-- name: GetBookByPath :one
SELECT id, series_id, library_id, name, path, size, file_modified_at, volume, title, summary, number, sort_number, page_count, cover_path, last_read_page, last_read_at, created_at, updated_at FROM books WHERE path = ? LIMIT 1
`

func (q *Queries) GetBookByPath(ctx context.Context, path string) (Book, error) {
	row := q.queryRow(ctx, q.getBookByPathStmt, getBookByPath, path)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Volume,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CoverPath,
		&i.LastReadPage,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, path, auto_scan, scan_interval, scan_formats, created_at FROM libraries WHERE id = ? LIMIT 1
`

func (q *Queries) GetLibrary(ctx context.Context, id int64) (Library, error) {
	row := q.queryRow(ctx, q.getLibraryStmt, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.AutoScan,
		&i.ScanInterval,
		&i.ScanFormats,
		&i.CreatedAt,
	)
	return i, err
}

const getLinksForSeries = `-- name: GetLinksForSeries :many
SELECT id, series_id, name, url, created_at FROM series_links WHERE series_id = ? ORDER BY id ASC
`

func (q *Queries) GetLinksForSeries(ctx context.Context, seriesID int64) ([]SeriesLink, error) {
	rows, err := q.query(ctx, q.getLinksForSeriesStmt, getLinksForSeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeriesLink
	for rows.Next() {
		var i SeriesLink
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Name,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextBookInSeries = `-- name: GetNextBookInSeries :one
SELECT nb.id, nb.series_id, nb.library_id, nb.name, nb.path, nb.size, nb.file_modified_at, nb.volume, nb.title, nb.summary, nb.number, nb.sort_number, nb.page_count, nb.cover_path, nb.last_read_page, nb.last_read_at, nb.created_at, nb.updated_at FROM books nb
INNER JOIN books cb ON cb.id = ? AND nb.series_id = cb.series_id
WHERE (nb.sort_number > cb.sort_number)
   OR (nb.sort_number = cb.sort_number AND nb.name > cb.name)
ORDER BY nb.sort_number, nb.name
LIMIT 1
`

func (q *Queries) GetNextBookInSeries(ctx context.Context, id int64) (Book, error) {
	row := q.queryRow(ctx, q.getNextBookInSeriesStmt, getNextBookInSeries, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Volume,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CoverPath,
		&i.LastReadPage,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentReadSeries = `-- name: GetRecentReadSeries :many
WITH RankedBooks AS (
    SELECT 
        b.series_id,
        b.id AS book_id,
        b.last_read_at,
        b.last_read_page,
        ROW_NUMBER() OVER(PARTITION BY b.series_id ORDER BY b.last_read_at DESC) as rn
    FROM books b
    WHERE b.last_read_at IS NOT NULL AND b.library_id = ?
)
SELECT 
    s.id, s.library_id, s.name, s.title, s.summary, s.publisher, s.status, s.rating, s.language, s.locked_fields, s.path, s.created_at, s.updated_at, s.is_favorite,
    rb.book_id AS recent_book_id,
    rb.last_read_at,
    rb.last_read_page,
    (SELECT b.cover_path FROM books b WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != '' ORDER BY b.sort_number, b.name LIMIT 1) as cover_path
FROM series s
JOIN RankedBooks rb ON s.id = rb.series_id AND rb.rn = 1
WHERE s.library_id = ?
ORDER BY rb.last_read_at DESC
LIMIT ?
`

type GetRecentReadSeriesParams struct {
	LibraryID   int64 `json:"library_id"`
	LibraryID_2 int64 `json:"library_id_2"`
	Limit       int64 `json:"limit"`
}

type GetRecentReadSeriesRow struct {
	ID           int64           `json:"id"`
	LibraryID    int64           `json:"library_id"`
	Name         string          `json:"name"`
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	Path         string          `json:"path"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	IsFavorite   bool            `json:"is_favorite"`
	RecentBookID int64           `json:"recent_book_id"`
	LastReadAt   sql.NullTime    `json:"last_read_at"`
	LastReadPage sql.NullInt64   `json:"last_read_page"`
	CoverPath    sql.NullString  `json:"cover_path"`
}

func (q *Queries) GetRecentReadSeries(ctx context.Context, arg GetRecentReadSeriesParams) ([]GetRecentReadSeriesRow, error) {
	rows, err := q.query(ctx, q.getRecentReadSeriesStmt, getRecentReadSeries, arg.LibraryID, arg.LibraryID_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentReadSeriesRow
	for rows.Next() {
		var i GetRecentReadSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Title,
			&i.Summary,
			&i.Publisher,
			&i.Status,
			&i.Rating,
			&i.Language,
			&i.LockedFields,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFavorite,
			&i.RecentBookID,
			&i.LastReadAt,
			&i.LastReadPage,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeries = `-- name: GetSeries :one
SELECT id, library_id, name, title, summary, publisher, status, rating, language, locked_fields, path, created_at, updated_at, is_favorite FROM series WHERE id = ? LIMIT 1
`

func (q *Queries) GetSeries(ctx context.Context, id int64) (Series, error) {
	row := q.queryRow(ctx, q.getSeriesStmt, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Title,
		&i.Summary,
		&i.Publisher,
		&i.Status,
		&i.Rating,
		&i.Language,
		&i.LockedFields,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsFavorite,
	)
	return i, err
}

const getSeriesByLibrary = `-- name: GetSeriesByLibrary :many
SELECT 
    s.id, s.library_id, s.name, s.title, s.summary, s.publisher, s.status, s.rating, s.language, s.locked_fields, s.path, s.created_at, s.updated_at, s.is_favorite, 
    GROUP_CONCAT(DISTINCT t.name) as tags_string,
    COUNT(DISTINCT NULLIF(b.volume, '')) as volume_count,
    COUNT(DISTINCT b.id) as actual_book_count,
    COUNT(DISTINCT CASE WHEN b.last_read_page > 0 THEN b.id END) as read_count,
    SUM(b.page_count) as total_pages
FROM series s
LEFT JOIN series_tags st ON s.id = st.series_id
LEFT JOIN tags t ON st.tag_id = t.id
LEFT JOIN books b ON s.id = b.series_id
WHERE s.library_id = ? 
GROUP BY s.id
ORDER BY s.name
`

type GetSeriesByLibraryRow struct {
	ID              int64           `json:"id"`
	LibraryID       int64           `json:"library_id"`
	Name            string          `json:"name"`
	Title           sql.NullString  `json:"title"`
	Summary         sql.NullString  `json:"summary"`
	Publisher       sql.NullString  `json:"publisher"`
	Status          sql.NullString  `json:"status"`
	Rating          sql.NullFloat64 `json:"rating"`
	Language        sql.NullString  `json:"language"`
	LockedFields    sql.NullString  `json:"locked_fields"`
	Path            string          `json:"path"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	IsFavorite      bool            `json:"is_favorite"`
	TagsString      string          `json:"tags_string"`
	VolumeCount     int64           `json:"volume_count"`
	ActualBookCount int64           `json:"actual_book_count"`
	ReadCount       int64           `json:"read_count"`
	TotalPages      sql.NullFloat64 `json:"total_pages"`
}

func (q *Queries) GetSeriesByLibrary(ctx context.Context, libraryID int64) ([]GetSeriesByLibraryRow, error) {
	rows, err := q.query(ctx, q.getSeriesByLibraryStmt, getSeriesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeriesByLibraryRow
	for rows.Next() {
		var i GetSeriesByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Title,
			&i.Summary,
			&i.Publisher,
			&i.Status,
			&i.Rating,
			&i.Language,
			&i.LockedFields,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFavorite,
			&i.TagsString,
			&i.VolumeCount,
			&i.ActualBookCount,
			&i.ReadCount,
			&i.TotalPages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForSeries = `-- name: GetTagsForSeries :many
SELECT t.id, t.name, t.created_at FROM tags t
JOIN series_tags st ON t.id = st.tag_id
WHERE st.series_id = ? ORDER BY t.name
`

func (q *Queries) GetTagsForSeries(ctx context.Context, seriesID int64) ([]Tag, error) {
	rows, err := q.query(ctx, q.getTagsForSeriesStmt, getTagsForSeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSeriesAuthor = `-- name: LinkSeriesAuthor :exec
INSERT OR IGNORE INTO series_authors (series_id, author_id) VALUES (?, ?)
`

type LinkSeriesAuthorParams struct {
	SeriesID int64 `json:"series_id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) LinkSeriesAuthor(ctx context.Context, arg LinkSeriesAuthorParams) error {
	_, err := q.exec(ctx, q.linkSeriesAuthorStmt, linkSeriesAuthor, arg.SeriesID, arg.AuthorID)
	return err
}

const linkSeriesLink = `-- name: LinkSeriesLink :one
INSERT INTO series_links (series_id, name, url) VALUES (?, ?, ?)
RETURNING id, series_id, name, url, created_at
`

type LinkSeriesLinkParams struct {
	SeriesID int64  `json:"series_id"`
	Name     string `json:"name"`
	Url      string `json:"url"`
}

func (q *Queries) LinkSeriesLink(ctx context.Context, arg LinkSeriesLinkParams) (SeriesLink, error) {
	row := q.queryRow(ctx, q.linkSeriesLinkStmt, linkSeriesLink, arg.SeriesID, arg.Name, arg.Url)
	var i SeriesLink
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const linkSeriesTag = `-- name: LinkSeriesTag :exec
INSERT OR IGNORE INTO series_tags (series_id, tag_id) VALUES (?, ?)
`

type LinkSeriesTagParams struct {
	SeriesID int64 `json:"series_id"`
	TagID    int64 `json:"tag_id"`
}

func (q *Queries) LinkSeriesTag(ctx context.Context, arg LinkSeriesTagParams) error {
	_, err := q.exec(ctx, q.linkSeriesTagStmt, linkSeriesTag, arg.SeriesID, arg.TagID)
	return err
}

const listBooksByLibrary = `-- name: ListBooksByLibrary :many
SELECT id, path, file_modified_at, size, cover_path FROM books WHERE library_id = ?
`

type ListBooksByLibraryRow struct {
	ID             int64          `json:"id"`
	Path           string         `json:"path"`
	FileModifiedAt time.Time      `json:"file_modified_at"`
	Size           int64          `json:"size"`
	CoverPath      sql.NullString `json:"cover_path"`
}

func (q *Queries) ListBooksByLibrary(ctx context.Context, libraryID int64) ([]ListBooksByLibraryRow, error) {
	rows, err := q.query(ctx, q.listBooksByLibraryStmt, listBooksByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksByLibraryRow
	for rows.Next() {
		var i ListBooksByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FileModifiedAt,
			&i.Size,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksBySeries = `-- name: ListBooksBySeries :many
SELECT id, series_id, library_id, name, path, size, file_modified_at, volume, title, summary, number, sort_number, page_count, cover_path, last_read_page, last_read_at, created_at, updated_at FROM books WHERE series_id = ? ORDER BY sort_number, name
`

func (q *Queries) ListBooksBySeries(ctx context.Context, seriesID int64) ([]Book, error) {
	rows, err := q.query(ctx, q.listBooksBySeriesStmt, listBooksBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.LibraryID,
			&i.Name,
			&i.Path,
			&i.Size,
			&i.FileModifiedAt,
			&i.Volume,
			&i.Title,
			&i.Summary,
			&i.Number,
			&i.SortNumber,
			&i.PageCount,
			&i.CoverPath,
			&i.LastReadPage,
			&i.LastReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, path, auto_scan, scan_interval, scan_formats, created_at FROM libraries ORDER BY name
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.query(ctx, q.listLibrariesStmt, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.AutoScan,
			&i.ScanInterval,
			&i.ScanFormats,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesByLibrary = `-- name: ListSeriesByLibrary :many
SELECT s.id, s.library_id, s.name, s.title, s.summary, s.publisher, s.status, s.rating, s.language, s.locked_fields, s.path, s.created_at, s.updated_at, s.is_favorite, 
       (SELECT b.cover_path 
        FROM books b 
        WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != ''
        ORDER BY b.sort_number, b.name 
        LIMIT 1) as cover_path 
FROM series s 
WHERE s.library_id = ? 
ORDER BY s.name
`

type ListSeriesByLibraryRow struct {
	ID           int64           `json:"id"`
	LibraryID    int64           `json:"library_id"`
	Name         string          `json:"name"`
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	Path         string          `json:"path"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	IsFavorite   bool            `json:"is_favorite"`
	CoverPath    sql.NullString  `json:"cover_path"`
}

func (q *Queries) ListSeriesByLibrary(ctx context.Context, libraryID int64) ([]ListSeriesByLibraryRow, error) {
	rows, err := q.query(ctx, q.listSeriesByLibraryStmt, listSeriesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesByLibraryRow
	for rows.Next() {
		var i ListSeriesByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Title,
			&i.Summary,
			&i.Publisher,
			&i.Status,
			&i.Rating,
			&i.Language,
			&i.LockedFields,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFavorite,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookProgress = `-- name: UpdateBookProgress :exec
UPDATE books 
SET last_read_page = ?, last_read_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateBookProgressParams struct {
	LastReadPage sql.NullInt64 `json:"last_read_page"`
	ID           int64         `json:"id"`
}

func (q *Queries) UpdateBookProgress(ctx context.Context, arg UpdateBookProgressParams) error {
	_, err := q.exec(ctx, q.updateBookProgressStmt, updateBookProgress, arg.LastReadPage, arg.ID)
	return err
}

const updateSeriesFavorite = `-- name: UpdateSeriesFavorite :exec
UPDATE series SET is_favorite = ? WHERE id = ?
`

type UpdateSeriesFavoriteParams struct {
	IsFavorite bool  `json:"is_favorite"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateSeriesFavorite(ctx context.Context, arg UpdateSeriesFavoriteParams) error {
	_, err := q.exec(ctx, q.updateSeriesFavoriteStmt, updateSeriesFavorite, arg.IsFavorite, arg.ID)
	return err
}

const updateSeriesMetadata = `-- name: UpdateSeriesMetadata :one
UPDATE series
SET 
    title = ?,
    summary = ?,
    publisher = ?,
    status = ?,
    rating = ?,
    language = ?,
    locked_fields = ?,
    is_favorite = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, library_id, name, title, summary, publisher, status, rating, language, locked_fields, path, created_at, updated_at, is_favorite
`

type UpdateSeriesMetadataParams struct {
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	IsFavorite   bool            `json:"is_favorite"`
	ID           int64           `json:"id"`
}

func (q *Queries) UpdateSeriesMetadata(ctx context.Context, arg UpdateSeriesMetadataParams) (Series, error) {
	row := q.queryRow(ctx, q.updateSeriesMetadataStmt, updateSeriesMetadata,
		arg.Title,
		arg.Summary,
		arg.Publisher,
		arg.Status,
		arg.Rating,
		arg.Language,
		arg.LockedFields,
		arg.IsFavorite,
		arg.ID,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Title,
		&i.Summary,
		&i.Publisher,
		&i.Status,
		&i.Rating,
		&i.Language,
		&i.LockedFields,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsFavorite,
	)
	return i, err
}

const upsertAuthor = `-- name: UpsertAuthor :one
INSERT INTO authors (name, role) VALUES (?, ?)
ON CONFLICT(name, role) DO UPDATE SET name = excluded.name, role=excluded.role
RETURNING id, name, role, created_at
`

type UpsertAuthorParams struct {
	Name string `json:"name"`
	Role string `json:"role"`
}

func (q *Queries) UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) (Author, error) {
	row := q.queryRow(ctx, q.upsertAuthorStmt, upsertAuthor, arg.Name, arg.Role)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const upsertBookByPath = `-- name: UpsertBookByPath :one
INSERT INTO books (
    series_id, library_id, name, path, size, file_modified_at, 
    volume, title, summary, number, sort_number, page_count, cover_path
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(path) DO UPDATE SET
    series_id = excluded.series_id,
    library_id = excluded.library_id,
    name = excluded.name,
    size = excluded.size,
    file_modified_at = excluded.file_modified_at,
    volume = excluded.volume,
    title = excluded.title,
    summary = excluded.summary,
    number = excluded.number,
    sort_number = excluded.sort_number,
    page_count = excluded.page_count,
    cover_path = excluded.cover_path,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, series_id, library_id, name, path, size, file_modified_at, volume, title, summary, number, sort_number, page_count, cover_path, last_read_page, last_read_at, created_at, updated_at
`

type UpsertBookByPathParams struct {
	SeriesID       int64           `json:"series_id"`
	LibraryID      int64           `json:"library_id"`
	Name           string          `json:"name"`
	Path           string          `json:"path"`
	Size           int64           `json:"size"`
	FileModifiedAt time.Time       `json:"file_modified_at"`
	Volume         string          `json:"volume"`
	Title          sql.NullString  `json:"title"`
	Summary        sql.NullString  `json:"summary"`
	Number         sql.NullString  `json:"number"`
	SortNumber     sql.NullFloat64 `json:"sort_number"`
	PageCount      int64           `json:"page_count"`
	CoverPath      sql.NullString  `json:"cover_path"`
}

func (q *Queries) UpsertBookByPath(ctx context.Context, arg UpsertBookByPathParams) (Book, error) {
	row := q.queryRow(ctx, q.upsertBookByPathStmt, upsertBookByPath,
		arg.SeriesID,
		arg.LibraryID,
		arg.Name,
		arg.Path,
		arg.Size,
		arg.FileModifiedAt,
		arg.Volume,
		arg.Title,
		arg.Summary,
		arg.Number,
		arg.SortNumber,
		arg.PageCount,
		arg.CoverPath,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Volume,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CoverPath,
		&i.LastReadPage,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSeriesByPath = `-- name: UpsertSeriesByPath :one
INSERT INTO series (
    library_id, name, path, title, summary, publisher, status, rating, language, locked_fields, is_favorite
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(path) DO UPDATE SET
    library_id = excluded.library_id,
    name = excluded.name,
    title = excluded.title,
    summary = excluded.summary,
    publisher = excluded.publisher,
    status = excluded.status,
    rating = excluded.rating,
    language = excluded.language,
    locked_fields = excluded.locked_fields,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, library_id, name, title, summary, publisher, status, rating, language, locked_fields, path, created_at, updated_at, is_favorite
`

type UpsertSeriesByPathParams struct {
	LibraryID    int64           `json:"library_id"`
	Name         string          `json:"name"`
	Path         string          `json:"path"`
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	IsFavorite   bool            `json:"is_favorite"`
}

func (q *Queries) UpsertSeriesByPath(ctx context.Context, arg UpsertSeriesByPathParams) (Series, error) {
	row := q.queryRow(ctx, q.upsertSeriesByPathStmt, upsertSeriesByPath,
		arg.LibraryID,
		arg.Name,
		arg.Path,
		arg.Title,
		arg.Summary,
		arg.Publisher,
		arg.Status,
		arg.Rating,
		arg.Language,
		arg.LockedFields,
		arg.IsFavorite,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Title,
		&i.Summary,
		&i.Publisher,
		&i.Status,
		&i.Rating,
		&i.Language,
		&i.LockedFields,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsFavorite,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = excluded.name
RETURNING id, name, created_at
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.queryRow(ctx, q.upsertTagStmt, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
