// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddReadingListItem(ctx context.Context, arg AddReadingListItemParams) (ReadingListItem, error)
	AddSeriesToCollection(ctx context.Context, arg AddSeriesToCollectionParams) error
	ClearAllBookCoverPaths(ctx context.Context) error
	ClearAllSeriesStatsCoverPaths(ctx context.Context) error
	ClearSeriesAuthors(ctx context.Context, seriesID int64) error
	ClearSeriesLinks(ctx context.Context, seriesID int64) error
	ClearSeriesTags(ctx context.Context, seriesID int64) error
	CollectionNameExists(ctx context.Context, name string) (int64, error)
	CountAIGroupingReviews(ctx context.Context, arg CountAIGroupingReviewsParams) (int64, error)
	CountAppliedAIGroupingReviewCollections(ctx context.Context, reviewID int64) (int64, error)
	CountHealthDuplicateFileHash(ctx context.Context, libraryID interface{}) (interface{}, error)
	CountHealthDuplicateQuickHash(ctx context.Context, libraryID interface{}) (interface{}, error)
	CountHealthEmptyPages(ctx context.Context, libraryID interface{}) (int64, error)
	CountHealthMissingCover(ctx context.Context, libraryID interface{}) (int64, error)
	CountHealthMissingMetadata(ctx context.Context, libraryID interface{}) (int64, error)
	CountHealthMissingQuickHash(ctx context.Context, libraryID interface{}) (int64, error)
	CountHealthUnmatchedKOReader(ctx context.Context) (int64, error)
	CountMihonSeries(ctx context.Context, arg CountMihonSeriesParams) (int64, error)
	CountOPDSSeriesSearch(ctx context.Context, query string) (int64, error)
	CountPendingAIGroupingReviewCollections(ctx context.Context, reviewID int64) (int64, error)
	CountPendingMetadataReviewInbox(ctx context.Context, arg CountPendingMetadataReviewInboxParams) (int64, error)
	CountReadingListSeries(ctx context.Context, readingListID int64) (int64, error)
	CountRecentAddedSeries(ctx context.Context, libraryID int64) (int64, error)
	CountSeriesByLibrary(ctx context.Context, libraryID int64) (int64, error)
	CreateAIGroupingReview(ctx context.Context, arg CreateAIGroupingReviewParams) (AiGroupingReview, error)
	CreateAIGroupingReviewCollection(ctx context.Context, arg CreateAIGroupingReviewCollectionParams) (AiGroupingReviewCollection, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	// Business note: this file is the database SQL contract layer. It defines the sqlc-generated
	// queries and the data operations the upper Store exposes. It directly shapes the meaning of
	// library, series-relation, reading-progress, task and search-sync data.
	// NOTE: keep this file ASCII-only. sqlc's SQLite parser mis-slices queries when the file contains
	// multi-byte (e.g. Chinese) characters, truncating query names and failing generation.
	// Section: Library queries define the root library objects; path, scan mode and format fields
	// directly affect how scan tasks discover comic files. Return columns become strongly-typed
	// sqlc methods, so column changes must stay in sync with schema, Store wrappers and the settings UI.
	CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error)
	CreateMetadataReview(ctx context.Context, arg CreateMetadataReviewParams) (MetadataReview, error)
	CreateMetadataReviewField(ctx context.Context, arg CreateMetadataReviewFieldParams) (MetadataReviewField, error)
	CreateReadingList(ctx context.Context, arg CreateReadingListParams) (ReadingList, error)
	CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error)
	CreateSeriesRelation(ctx context.Context, arg CreateSeriesRelationParams) error
	CreateSimpleCollection(ctx context.Context, arg CreateSimpleCollectionParams) (int64, error)
	DeleteBook(ctx context.Context, id int64) error
	DeleteBookByPath(ctx context.Context, path string) error
	DeleteCollection(ctx context.Context, id int64) error
	DeleteFranchiseCollections(ctx context.Context) error
	DeleteLibrary(ctx context.Context, id int64) error
	DeleteReadingBookmark(ctx context.Context, arg DeleteReadingBookmarkParams) (int64, error)
	DeleteReadingList(ctx context.Context, id int64) error
	DeleteSeries(ctx context.Context, id int64) error
	DeleteSeriesRelation(ctx context.Context, id int64) error
	DeleteSmartFilter(ctx context.Context, id int64) (int64, error)
	FindExistingSeriesRelation(ctx context.Context, arg FindExistingSeriesRelationParams) (int64, error)
	GetAIGroupingReview(ctx context.Context, id int64) (AiGroupingReview, error)
	GetAIGroupingReviewCollection(ctx context.Context, id int64) (AiGroupingReviewCollection, error)
	GetActivityHeatmap(ctx context.Context, offsetClause interface{}) ([]GetActivityHeatmapRow, error)
	GetAllAuthors(ctx context.Context) ([]Author, error)
	GetAllSeriesRelations(ctx context.Context) ([]SeriesRelation, error)
	GetAllSeriesRelationsForLibrary(ctx context.Context, arg GetAllSeriesRelationsForLibraryParams) ([]GetAllSeriesRelationsForLibraryRow, error)
	GetAllTags(ctx context.Context) ([]Tag, error)
	GetAuthorsForSeries(ctx context.Context, seriesID int64) ([]Author, error)
	GetBook(ctx context.Context, id int64) (Book, error)
	GetBookByPath(ctx context.Context, path string) (Book, error)
	GetBookCoverPath(ctx context.Context, id int64) (string, error)
	GetBookCoverPathsByIDs(ctx context.Context, ids []int64) ([]GetBookCoverPathsByIDsRow, error)
	GetCandidateSeriesForAI(ctx context.Context, limit int64) ([]GetCandidateSeriesForAIRow, error)
	GetConnectedSeriesRelations(ctx context.Context, startSeriesID int64) ([]GetConnectedSeriesRelationsRow, error)
	GetContinueReadingSequels(ctx context.Context) ([]GetContinueReadingSequelsRow, error)
	GetDashboardCoreStats(ctx context.Context) (GetDashboardCoreStatsRow, error)
	GetLastTaskKeyForScope(ctx context.Context, arg GetLastTaskKeyForScopeParams) (string, error)
	GetLibrary(ctx context.Context, id int64) (Library, error)
	GetLinksForSeries(ctx context.Context, seriesID int64) ([]SeriesLink, error)
	GetMetadataReview(ctx context.Context, id int64) (MetadataReview, error)
	GetMihonSeries(ctx context.Context, id int64) (GetMihonSeriesRow, error)
	GetNextBookInSeries(ctx context.Context, id int64) (Book, error)
	GetReadingList(ctx context.Context, id int64) (ReadingList, error)
	GetReadingListItemProgressByList(ctx context.Context, readingListID int64) ([]GetReadingListItemProgressByListRow, error)
	GetRecentReadAll(ctx context.Context, limit int64) ([]GetRecentReadAllRow, error)
	GetRecentReadSeries(ctx context.Context, arg GetRecentReadSeriesParams) ([]GetRecentReadSeriesRow, error)
	GetRecommendations(ctx context.Context, limit int64) ([]GetRecommendationsRow, error)
	GetReferencedBookCoverPaths(ctx context.Context) ([]sql.NullString, error)
	GetReferencedSeriesCoverPaths(ctx context.Context) ([]string, error)
	GetSeries(ctx context.Context, id int64) (Series, error)
	GetSeriesByLibrary(ctx context.Context, libraryID int64) ([]GetSeriesByLibraryRow, error)
	GetSeriesCoverPathsByIDs(ctx context.Context, ids []int64) ([]GetSeriesCoverPathsByIDsRow, error)
	GetSeriesIDByBookID(ctx context.Context, id int64) (int64, error)
	GetSeriesIDByBookPath(ctx context.Context, path string) (int64, error)
	GetSeriesMetadataProvenance(ctx context.Context, seriesID int64) ([]SeriesMetadataProvenance, error)
	GetSeriesNamesByIDs(ctx context.Context, ids []int64) ([]GetSeriesNamesByIDsRow, error)
	GetSeriesWithoutCollection(ctx context.Context, libraryID int64) ([]GetSeriesWithoutCollectionRow, error)
	GetSmartFilterByID(ctx context.Context, id int64) (SmartFilter, error)
	GetStaticCollectionView(ctx context.Context, id int64) (GetStaticCollectionViewRow, error)
	GetTagsForSeries(ctx context.Context, seriesID int64) ([]Tag, error)
	GetTopReadingTags(ctx context.Context, limit int64) ([]GetTopReadingTagsRow, error)
	LinkSeriesAuthor(ctx context.Context, arg LinkSeriesAuthorParams) error
	LinkSeriesLink(ctx context.Context, arg LinkSeriesLinkParams) (SeriesLink, error)
	LinkSeriesTag(ctx context.Context, arg LinkSeriesTagParams) error
	ListAIGroupingReviewCollections(ctx context.Context, reviewID int64) ([]AiGroupingReviewCollection, error)
	ListAIGroupingReviews(ctx context.Context, arg ListAIGroupingReviewsParams) ([]ListAIGroupingReviewsRow, error)
	ListBooksByLibrary(ctx context.Context, libraryID int64) ([]ListBooksByLibraryRow, error)
	ListBooksBySeries(ctx context.Context, seriesID int64) ([]Book, error)
	ListCollectionSeries(ctx context.Context, collectionID int64) ([]ListCollectionSeriesRow, error)
	ListCollectionViews(ctx context.Context) ([]ListCollectionViewsRow, error)
	ListCollectionsWithSeriesCount(ctx context.Context) ([]ListCollectionsWithSeriesCountRow, error)
	ListExternalLibraryBooks(ctx context.Context, libraryID int64) ([]ListExternalLibraryBooksRow, error)
	ListForwardSeriesRelations(ctx context.Context, sourceSeriesID int64) ([]ListForwardSeriesRelationsRow, error)
	ListHealthDuplicateFileHash(ctx context.Context, arg ListHealthDuplicateFileHashParams) ([]ListHealthDuplicateFileHashRow, error)
	ListHealthDuplicateQuickHash(ctx context.Context, arg ListHealthDuplicateQuickHashParams) ([]ListHealthDuplicateQuickHashRow, error)
	ListHealthEmptyPages(ctx context.Context, arg ListHealthEmptyPagesParams) ([]ListHealthEmptyPagesRow, error)
	ListHealthMissingCover(ctx context.Context, arg ListHealthMissingCoverParams) ([]ListHealthMissingCoverRow, error)
	ListHealthMissingMetadata(ctx context.Context, arg ListHealthMissingMetadataParams) ([]ListHealthMissingMetadataRow, error)
	ListHealthMissingQuickHash(ctx context.Context, arg ListHealthMissingQuickHashParams) ([]ListHealthMissingQuickHashRow, error)
	ListHealthUnmatchedKOReader(ctx context.Context, limit int64) ([]ListHealthUnmatchedKOReaderRow, error)
	ListLibraries(ctx context.Context) ([]Library, error)
	ListLibrarySizes(ctx context.Context) ([]ListLibrarySizesRow, error)
	ListMetadataReviewFields(ctx context.Context, reviewID int64) ([]MetadataReviewField, error)
	ListMetadataReviewFieldsByReviews(ctx context.Context, reviewIds []int64) ([]MetadataReviewField, error)
	ListMetadataReviewsBySeries(ctx context.Context, seriesID int64) ([]MetadataReview, error)
	ListMihonSeries(ctx context.Context, arg ListMihonSeriesParams) ([]ListMihonSeriesRow, error)
	ListMihonSeriesByBooks(ctx context.Context, arg ListMihonSeriesByBooksParams) ([]ListMihonSeriesByBooksRow, error)
	ListMihonSeriesByUpdated(ctx context.Context, arg ListMihonSeriesByUpdatedParams) ([]ListMihonSeriesByUpdatedRow, error)
	ListOPDSLibrarySeriesPaged(ctx context.Context, arg ListOPDSLibrarySeriesPagedParams) ([]ListOPDSLibrarySeriesPagedRow, error)
	ListPendingMetadataReviewInbox(ctx context.Context, arg ListPendingMetadataReviewInboxParams) ([]ListPendingMetadataReviewInboxRow, error)
	ListPendingMetadataReviewsBySeries(ctx context.Context, seriesID int64) ([]MetadataReview, error)
	ListReadingBookmarks(ctx context.Context, bookID int64) ([]ReadingBookmark, error)
	ListReadingListItems(ctx context.Context, readingListID int64) ([]ListReadingListItemsRow, error)
	ListReadingListSeriesPage(ctx context.Context, arg ListReadingListSeriesPageParams) ([]ListReadingListSeriesPageRow, error)
	ListReadingLists(ctx context.Context) ([]ListReadingListsRow, error)
	ListRecentAddedSeries(ctx context.Context, arg ListRecentAddedSeriesParams) ([]ListRecentAddedSeriesRow, error)
	ListReverseSeriesRelations(ctx context.Context, targetSeriesID int64) ([]ListReverseSeriesRelationsRow, error)
	ListSeriesByLibrary(ctx context.Context, libraryID int64) ([]ListSeriesByLibraryRow, error)
	ListSeriesInitialBackfillCandidates(ctx context.Context) ([]ListSeriesInitialBackfillCandidatesRow, error)
	ListSmartFiltersByLibrary(ctx context.Context, libraryID int64) ([]SmartFilter, error)
	ListStaticCollectionSeriesPaged(ctx context.Context, arg ListStaticCollectionSeriesPagedParams) ([]ListStaticCollectionSeriesPagedRow, error)
	LogReadingActivity(ctx context.Context, arg LogReadingActivityParams) error
	MarkAIGroupingReviewCollectionApplied(ctx context.Context, arg MarkAIGroupingReviewCollectionAppliedParams) error
	MarkAIGroupingReviewCollectionRejected(ctx context.Context, id int64) error
	MarkAIGroupingReviewCollectionsRejected(ctx context.Context, reviewID int64) error
	MarkInterruptedTasks(ctx context.Context, arg MarkInterruptedTasksParams) (int64, error)
	RefreshSeriesStats(ctx context.Context, id int64) error
	RemoveReadingListItem(ctx context.Context, arg RemoveReadingListItemParams) error
	RemoveSeriesFromCollection(ctx context.Context, arg RemoveSeriesFromCollectionParams) error
	SearchOPDSSeries(ctx context.Context, arg SearchOPDSSeriesParams) ([]SearchOPDSSeriesRow, error)
	SeriesExistsByID(ctx context.Context, id int64) (int64, error)
	SetBookCoverIfMissing(ctx context.Context, arg SetBookCoverIfMissingParams) (int64, error)
	TouchCollection(ctx context.Context, id int64) error
	UpdateAIGroupingReviewCollection(ctx context.Context, arg UpdateAIGroupingReviewCollectionParams) (AiGroupingReviewCollection, error)
	UpdateAIGroupingReviewStatus(ctx context.Context, arg UpdateAIGroupingReviewStatusParams) (AiGroupingReview, error)
	UpdateBookProgress(ctx context.Context, arg UpdateBookProgressParams) error
	UpdateCollectionDetails(ctx context.Context, arg UpdateCollectionDetailsParams) error
	UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error)
	UpdateMetadataReviewStatus(ctx context.Context, arg UpdateMetadataReviewStatusParams) (MetadataReview, error)
	UpdateReadingList(ctx context.Context, arg UpdateReadingListParams) (ReadingList, error)
	UpdateReadingListItemSortOrder(ctx context.Context, arg UpdateReadingListItemSortOrderParams) error
	UpdateSeriesFavorite(ctx context.Context, arg UpdateSeriesFavoriteParams) error
	UpdateSeriesInitial(ctx context.Context, arg UpdateSeriesInitialParams) error
	UpdateSeriesMetadata(ctx context.Context, arg UpdateSeriesMetadataParams) (Series, error)
	UpdateSeriesRelation(ctx context.Context, arg UpdateSeriesRelationParams) error
	UpdateSeriesStatistics(ctx context.Context, arg UpdateSeriesStatisticsParams) error
	UpdateSmartFilter(ctx context.Context, arg UpdateSmartFilterParams) (SmartFilter, error)
	UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) (Author, error)
	UpsertBookByPath(ctx context.Context, arg UpsertBookByPathParams) (Book, error)
	UpsertReadingBookmark(ctx context.Context, arg UpsertReadingBookmarkParams) (ReadingBookmark, error)
	UpsertSeriesByPath(ctx context.Context, arg UpsertSeriesByPathParams) (Series, error)
	UpsertSeriesMetadataProvenance(ctx context.Context, arg UpsertSeriesMetadataProvenanceParams) (SeriesMetadataProvenance, error)
	UpsertSmartFilter(ctx context.Context, arg UpsertSmartFilterParams) (SmartFilter, error)
	UpsertTag(ctx context.Context, name string) (Tag, error)
	UpsertTaskRecord(ctx context.Context, arg UpsertTaskRecordParams) error
}

var _ Querier = (*Queries)(nil)
