// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateBookPage(ctx context.Context, arg CreateBookPageParams) (BookPage, error)
	CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error)
	CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error)
	DeleteBookByPath(ctx context.Context, path string) error
	GetBook(ctx context.Context, id string) (Book, error)
	GetLibrary(ctx context.Context, id string) (Library, error)
	GetSeries(ctx context.Context, id string) (Series, error)
	ListBookPages(ctx context.Context, bookID string) ([]BookPage, error)
	ListBooksByLibrary(ctx context.Context, libraryID string) ([]ListBooksByLibraryRow, error)
	ListBooksBySeries(ctx context.Context, seriesID string) ([]Book, error)
	ListLibraries(ctx context.Context) ([]Library, error)
	ListSeriesByLibrary(ctx context.Context, libraryID string) ([]Series, error)
}

var _ Querier = (*Queries)(nil)
