// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	AddReadingListItem(ctx context.Context, arg AddReadingListItemParams) (ReadingListItem, error)
	ClearSeriesAuthors(ctx context.Context, seriesID int64) error
	ClearSeriesLinks(ctx context.Context, seriesID int64) error
	ClearSeriesTags(ctx context.Context, seriesID int64) error
	CountMihonSeries(ctx context.Context, arg CountMihonSeriesParams) (int64, error)
	CountOPDSSeriesSearch(ctx context.Context, query string) (int64, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error)
	CreateReadingList(ctx context.Context, arg CreateReadingListParams) (ReadingList, error)
	CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error)
	DeleteBook(ctx context.Context, id int64) error
	DeleteBookByPath(ctx context.Context, path string) error
	DeleteLibrary(ctx context.Context, id int64) error
	DeleteReadingList(ctx context.Context, id int64) error
	DeleteSeries(ctx context.Context, id int64) error
	GetAllAuthors(ctx context.Context) ([]Author, error)
	GetAllTags(ctx context.Context) ([]Tag, error)
	GetAuthorsForSeries(ctx context.Context, seriesID int64) ([]Author, error)
	GetBook(ctx context.Context, id int64) (Book, error)
	GetBookByPath(ctx context.Context, path string) (Book, error)
	GetCandidateSeriesForAI(ctx context.Context, limit int64) ([]GetCandidateSeriesForAIRow, error)
	GetLibrary(ctx context.Context, id int64) (Library, error)
	GetLinksForSeries(ctx context.Context, seriesID int64) ([]SeriesLink, error)
	GetMihonSeries(ctx context.Context, id int64) (GetMihonSeriesRow, error)
	GetNextBookInSeries(ctx context.Context, id int64) (Book, error)
	GetReadingList(ctx context.Context, id int64) (ReadingList, error)
	GetRecentReadSeries(ctx context.Context, arg GetRecentReadSeriesParams) ([]GetRecentReadSeriesRow, error)
	GetSeries(ctx context.Context, id int64) (Series, error)
	GetSeriesByLibrary(ctx context.Context, libraryID int64) ([]GetSeriesByLibraryRow, error)
	GetSeriesWithoutCollection(ctx context.Context, libraryID int64) ([]GetSeriesWithoutCollectionRow, error)
	GetTagsForSeries(ctx context.Context, seriesID int64) ([]Tag, error)
	GetTopReadingTags(ctx context.Context, limit int64) ([]GetTopReadingTagsRow, error)
	LinkSeriesAuthor(ctx context.Context, arg LinkSeriesAuthorParams) error
	LinkSeriesLink(ctx context.Context, arg LinkSeriesLinkParams) (SeriesLink, error)
	LinkSeriesTag(ctx context.Context, arg LinkSeriesTagParams) error
	ListBooksByLibrary(ctx context.Context, libraryID int64) ([]ListBooksByLibraryRow, error)
	ListBooksBySeries(ctx context.Context, seriesID int64) ([]Book, error)
	ListLibraries(ctx context.Context) ([]Library, error)
	ListMihonSeries(ctx context.Context, arg ListMihonSeriesParams) ([]ListMihonSeriesRow, error)
	ListMihonSeriesByBooks(ctx context.Context, arg ListMihonSeriesByBooksParams) ([]ListMihonSeriesByBooksRow, error)
	ListMihonSeriesByUpdated(ctx context.Context, arg ListMihonSeriesByUpdatedParams) ([]ListMihonSeriesByUpdatedRow, error)
	ListReadingListItems(ctx context.Context, readingListID int64) ([]ListReadingListItemsRow, error)
	ListReadingLists(ctx context.Context) ([]ListReadingListsRow, error)
	ListSeriesByLibrary(ctx context.Context, libraryID int64) ([]ListSeriesByLibraryRow, error)
	ListSeriesInitialBackfillCandidates(ctx context.Context) ([]ListSeriesInitialBackfillCandidatesRow, error)
	RemoveReadingListItem(ctx context.Context, arg RemoveReadingListItemParams) error
	SearchOPDSSeries(ctx context.Context, arg SearchOPDSSeriesParams) ([]SearchOPDSSeriesRow, error)
	UpdateBookProgress(ctx context.Context, arg UpdateBookProgressParams) error
	UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error)
	UpdateReadingList(ctx context.Context, arg UpdateReadingListParams) (ReadingList, error)
	UpdateReadingListItemSortOrder(ctx context.Context, arg UpdateReadingListItemSortOrderParams) error
	UpdateSeriesFavorite(ctx context.Context, arg UpdateSeriesFavoriteParams) error
	UpdateSeriesInitial(ctx context.Context, arg UpdateSeriesInitialParams) error
	UpdateSeriesMetadata(ctx context.Context, arg UpdateSeriesMetadataParams) (Series, error)
	UpdateSeriesStatistics(ctx context.Context, arg UpdateSeriesStatisticsParams) error
	UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) (Author, error)
	UpsertBookByPath(ctx context.Context, arg UpsertBookByPathParams) (Book, error)
	UpsertSeriesByPath(ctx context.Context, arg UpsertSeriesByPathParams) (Series, error)
	UpsertTag(ctx context.Context, name string) (Tag, error)
}

var _ Querier = (*Queries)(nil)
