// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    id, series_id, library_id, name, path, size, file_modified_at, 
    title, summary, number, sort_number, page_count
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, series_id, library_id, name, path, size, file_modified_at, title, summary, number, sort_number, page_count, created_at, updated_at
`

type CreateBookParams struct {
	ID             string          `json:"id"`
	SeriesID       string          `json:"series_id"`
	LibraryID      string          `json:"library_id"`
	Name           string          `json:"name"`
	Path           string          `json:"path"`
	Size           int64           `json:"size"`
	FileModifiedAt time.Time       `json:"file_modified_at"`
	Title          sql.NullString  `json:"title"`
	Summary        sql.NullString  `json:"summary"`
	Number         sql.NullString  `json:"number"`
	SortNumber     sql.NullFloat64 `json:"sort_number"`
	PageCount      int64           `json:"page_count"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.queryRow(ctx, q.createBookStmt, createBook,
		arg.ID,
		arg.SeriesID,
		arg.LibraryID,
		arg.Name,
		arg.Path,
		arg.Size,
		arg.FileModifiedAt,
		arg.Title,
		arg.Summary,
		arg.Number,
		arg.SortNumber,
		arg.PageCount,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBookPage = `-- name: CreateBookPage :one
INSERT INTO book_pages (
    id, book_id, file_name, media_type, number, size, width, height
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, book_id, file_name, media_type, number, size, width, height, created_at
`

type CreateBookPageParams struct {
	ID        string        `json:"id"`
	BookID    string        `json:"book_id"`
	FileName  string        `json:"file_name"`
	MediaType string        `json:"media_type"`
	Number    int64         `json:"number"`
	Size      int64         `json:"size"`
	Width     sql.NullInt64 `json:"width"`
	Height    sql.NullInt64 `json:"height"`
}

func (q *Queries) CreateBookPage(ctx context.Context, arg CreateBookPageParams) (BookPage, error) {
	row := q.queryRow(ctx, q.createBookPageStmt, createBookPage,
		arg.ID,
		arg.BookID,
		arg.FileName,
		arg.MediaType,
		arg.Number,
		arg.Size,
		arg.Width,
		arg.Height,
	)
	var i BookPage
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.FileName,
		&i.MediaType,
		&i.Number,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO libraries (id, name, path)
VALUES (?, ?, ?)
RETURNING id, name, path, created_at, updated_at
`

type CreateLibraryParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Path string `json:"path"`
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.queryRow(ctx, q.createLibraryStmt, createLibrary, arg.ID, arg.Name, arg.Path)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (
    id, library_id, name, path, title, summary, publisher, status
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, library_id, name, path, title, summary, publisher, status, created_at, updated_at
`

type CreateSeriesParams struct {
	ID        string         `json:"id"`
	LibraryID string         `json:"library_id"`
	Name      string         `json:"name"`
	Path      string         `json:"path"`
	Title     sql.NullString `json:"title"`
	Summary   sql.NullString `json:"summary"`
	Publisher sql.NullString `json:"publisher"`
	Status    sql.NullString `json:"status"`
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.queryRow(ctx, q.createSeriesStmt, createSeries,
		arg.ID,
		arg.LibraryID,
		arg.Name,
		arg.Path,
		arg.Title,
		arg.Summary,
		arg.Publisher,
		arg.Status,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Title,
		&i.Summary,
		&i.Publisher,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBookByPath = `-- name: DeleteBookByPath :exec
DELETE FROM books WHERE path = ?
`

func (q *Queries) DeleteBookByPath(ctx context.Context, path string) error {
	_, err := q.exec(ctx, q.deleteBookByPathStmt, deleteBookByPath, path)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, series_id, library_id, name, path, size, file_modified_at, title, summary, number, sort_number, page_count, created_at, updated_at FROM books WHERE id = ? LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id string) (Book, error) {
	row := q.queryRow(ctx, q.getBookStmt, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, path, created_at, updated_at FROM libraries WHERE id = ? LIMIT 1
`

func (q *Queries) GetLibrary(ctx context.Context, id string) (Library, error) {
	row := q.queryRow(ctx, q.getLibraryStmt, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeries = `-- name: GetSeries :one
SELECT id, library_id, name, path, title, summary, publisher, status, created_at, updated_at FROM series WHERE id = ? LIMIT 1
`

func (q *Queries) GetSeries(ctx context.Context, id string) (Series, error) {
	row := q.queryRow(ctx, q.getSeriesStmt, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Title,
		&i.Summary,
		&i.Publisher,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookPages = `-- name: ListBookPages :many
SELECT id, book_id, file_name, media_type, number, size, width, height, created_at FROM book_pages WHERE book_id = ? ORDER BY number
`

func (q *Queries) ListBookPages(ctx context.Context, bookID string) ([]BookPage, error) {
	rows, err := q.query(ctx, q.listBookPagesStmt, listBookPages, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookPage
	for rows.Next() {
		var i BookPage
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.FileName,
			&i.MediaType,
			&i.Number,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksByLibrary = `-- name: ListBooksByLibrary :many
SELECT id, path, file_modified_at, size FROM books WHERE library_id = ?
`

type ListBooksByLibraryRow struct {
	ID             string    `json:"id"`
	Path           string    `json:"path"`
	FileModifiedAt time.Time `json:"file_modified_at"`
	Size           int64     `json:"size"`
}

func (q *Queries) ListBooksByLibrary(ctx context.Context, libraryID string) ([]ListBooksByLibraryRow, error) {
	rows, err := q.query(ctx, q.listBooksByLibraryStmt, listBooksByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksByLibraryRow
	for rows.Next() {
		var i ListBooksByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FileModifiedAt,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksBySeries = `-- name: ListBooksBySeries :many
SELECT id, series_id, library_id, name, path, size, file_modified_at, title, summary, number, sort_number, page_count, created_at, updated_at FROM books WHERE series_id = ? ORDER BY sort_number, name
`

func (q *Queries) ListBooksBySeries(ctx context.Context, seriesID string) ([]Book, error) {
	rows, err := q.query(ctx, q.listBooksBySeriesStmt, listBooksBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.LibraryID,
			&i.Name,
			&i.Path,
			&i.Size,
			&i.FileModifiedAt,
			&i.Title,
			&i.Summary,
			&i.Number,
			&i.SortNumber,
			&i.PageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, path, created_at, updated_at FROM libraries ORDER BY name
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.query(ctx, q.listLibrariesStmt, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesByLibrary = `-- name: ListSeriesByLibrary :many
SELECT id, library_id, name, path, title, summary, publisher, status, created_at, updated_at FROM series WHERE library_id = ? ORDER BY name
`

func (q *Queries) ListSeriesByLibrary(ctx context.Context, libraryID string) ([]Series, error) {
	rows, err := q.query(ctx, q.listSeriesByLibraryStmt, listSeriesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Path,
			&i.Title,
			&i.Summary,
			&i.Publisher,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
