// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const addReadingListItem = `-- name: AddReadingListItem :one
INSERT INTO reading_list_items (reading_list_id, series_id, sort_order, note)
VALUES (
    ?1,
    ?2,
    COALESCE((SELECT MAX(sort_order) + 10 FROM reading_list_items WHERE reading_list_id = ?1), 10),
    ?3
)
ON CONFLICT(reading_list_id, series_id) DO UPDATE SET
    note = excluded.note,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, reading_list_id, series_id, sort_order, note, created_at, updated_at
`

type AddReadingListItemParams struct {
	ReadingListID int64  `json:"reading_list_id"`
	SeriesID      int64  `json:"series_id"`
	Note          string `json:"note"`
}

func (q *Queries) AddReadingListItem(ctx context.Context, arg AddReadingListItemParams) (ReadingListItem, error) {
	row := q.queryRow(ctx, q.addReadingListItemStmt, addReadingListItem, arg.ReadingListID, arg.SeriesID, arg.Note)
	var i ReadingListItem
	err := row.Scan(
		&i.ID,
		&i.ReadingListID,
		&i.SeriesID,
		&i.SortOrder,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addSeriesToCollection = `-- name: AddSeriesToCollection :exec
INSERT OR IGNORE INTO collection_series (collection_id, series_id)
VALUES (?, ?)
`

type AddSeriesToCollectionParams struct {
	CollectionID int64 `json:"collection_id"`
	SeriesID     int64 `json:"series_id"`
}

func (q *Queries) AddSeriesToCollection(ctx context.Context, arg AddSeriesToCollectionParams) error {
	_, err := q.exec(ctx, q.addSeriesToCollectionStmt, addSeriesToCollection, arg.CollectionID, arg.SeriesID)
	return err
}

const clearSeriesAuthors = `-- name: ClearSeriesAuthors :exec
DELETE FROM series_authors WHERE series_id = ?
`

func (q *Queries) ClearSeriesAuthors(ctx context.Context, seriesID int64) error {
	_, err := q.exec(ctx, q.clearSeriesAuthorsStmt, clearSeriesAuthors, seriesID)
	return err
}

const clearSeriesLinks = `-- name: ClearSeriesLinks :exec
DELETE FROM series_links WHERE series_id = ?
`

func (q *Queries) ClearSeriesLinks(ctx context.Context, seriesID int64) error {
	_, err := q.exec(ctx, q.clearSeriesLinksStmt, clearSeriesLinks, seriesID)
	return err
}

const clearSeriesTags = `-- name: ClearSeriesTags :exec
DELETE FROM series_tags WHERE series_id = ?
`

func (q *Queries) ClearSeriesTags(ctx context.Context, seriesID int64) error {
	_, err := q.exec(ctx, q.clearSeriesTagsStmt, clearSeriesTags, seriesID)
	return err
}

const countAIGroupingReviews = `-- name: CountAIGroupingReviews :one
SELECT COUNT(*)
FROM ai_grouping_reviews agr
WHERE (CAST(?1 AS INTEGER) = 0 OR agr.library_id = CAST(?1 AS INTEGER))
  AND (CAST(?2 AS TEXT) = '' OR agr.status = CAST(?2 AS TEXT))
`

type CountAIGroupingReviewsParams struct {
	LibraryID int64  `json:"library_id"`
	Status    string `json:"status"`
}

func (q *Queries) CountAIGroupingReviews(ctx context.Context, arg CountAIGroupingReviewsParams) (int64, error) {
	row := q.queryRow(ctx, q.countAIGroupingReviewsStmt, countAIGroupingReviews, arg.LibraryID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMihonSeries = `-- name: CountMihonSeries :one
SELECT COUNT(*)
FROM series s
WHERE (CAST(?1 AS INTEGER) = 0 OR s.library_id = CAST(?1 AS INTEGER))
  AND (
    CAST(?2 AS TEXT) = ''
    OR instr(lower(s.name), lower(CAST(?2 AS TEXT))) > 0
    OR instr(lower(COALESCE(s.title, '')), lower(CAST(?2 AS TEXT))) > 0
  )
`

type CountMihonSeriesParams struct {
	LibraryID int64  `json:"library_id"`
	Query     string `json:"query"`
}

func (q *Queries) CountMihonSeries(ctx context.Context, arg CountMihonSeriesParams) (int64, error) {
	row := q.queryRow(ctx, q.countMihonSeriesStmt, countMihonSeries, arg.LibraryID, arg.Query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOPDSSeriesSearch = `-- name: CountOPDSSeriesSearch :one
SELECT COUNT(*)
FROM series s
WHERE instr(lower(s.name), lower(?1)) > 0
   OR instr(lower(COALESCE(s.title, '')), lower(?1)) > 0
`

func (q *Queries) CountOPDSSeriesSearch(ctx context.Context, query string) (int64, error) {
	row := q.queryRow(ctx, q.countOPDSSeriesSearchStmt, countOPDSSeriesSearch, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingMetadataReviewInbox = `-- name: CountPendingMetadataReviewInbox :one
SELECT COUNT(*)
FROM metadata_reviews mr
JOIN series s ON s.id = mr.series_id
JOIN libraries l ON l.id = s.library_id
WHERE mr.status = 'pending'
  AND (CAST(?1 AS INTEGER) = 0 OR s.library_id = CAST(?1 AS INTEGER))
  AND (CAST(?2 AS TEXT) = '' OR lower(mr.provider) = lower(CAST(?2 AS TEXT)))
  AND (
    CAST(?3 AS TEXT) = ''
    OR instr(lower(s.name), lower(CAST(?3 AS TEXT))) > 0
    OR instr(lower(COALESCE(s.title, '')), lower(CAST(?3 AS TEXT))) > 0
    OR instr(lower(mr.source_query), lower(CAST(?3 AS TEXT))) > 0
  )
`

type CountPendingMetadataReviewInboxParams struct {
	LibraryID int64  `json:"library_id"`
	Provider  string `json:"provider"`
	Query     string `json:"query"`
}

func (q *Queries) CountPendingMetadataReviewInbox(ctx context.Context, arg CountPendingMetadataReviewInboxParams) (int64, error) {
	row := q.queryRow(ctx, q.countPendingMetadataReviewInboxStmt, countPendingMetadataReviewInbox, arg.LibraryID, arg.Provider, arg.Query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAIGroupingReview = `-- name: CreateAIGroupingReview :one
INSERT INTO ai_grouping_reviews (
    library_id, provider, status, summary, raw_payload, candidate_count, collection_count
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7
)
RETURNING id, library_id, provider, status, summary, raw_payload, candidate_count, collection_count, created_at, updated_at, applied_at, rejected_at
`

type CreateAIGroupingReviewParams struct {
	LibraryID       int64  `json:"library_id"`
	Provider        string `json:"provider"`
	Status          string `json:"status"`
	Summary         string `json:"summary"`
	RawPayload      string `json:"raw_payload"`
	CandidateCount  int64  `json:"candidate_count"`
	CollectionCount int64  `json:"collection_count"`
}

func (q *Queries) CreateAIGroupingReview(ctx context.Context, arg CreateAIGroupingReviewParams) (AiGroupingReview, error) {
	row := q.queryRow(ctx, q.createAIGroupingReviewStmt, createAIGroupingReview,
		arg.LibraryID,
		arg.Provider,
		arg.Status,
		arg.Summary,
		arg.RawPayload,
		arg.CandidateCount,
		arg.CollectionCount,
	)
	var i AiGroupingReview
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Provider,
		&i.Status,
		&i.Summary,
		&i.RawPayload,
		&i.CandidateCount,
		&i.CollectionCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppliedAt,
		&i.RejectedAt,
	)
	return i, err
}

const createAIGroupingReviewCollection = `-- name: CreateAIGroupingReviewCollection :one
INSERT INTO ai_grouping_review_collections (
    review_id, name, description, series_ids, series_count, status
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6
)
RETURNING id, review_id, name, description, series_ids, series_count, status, created_collection_id, created_at, updated_at
`

type CreateAIGroupingReviewCollectionParams struct {
	ReviewID    int64  `json:"review_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	SeriesIds   string `json:"series_ids"`
	SeriesCount int64  `json:"series_count"`
	Status      string `json:"status"`
}

func (q *Queries) CreateAIGroupingReviewCollection(ctx context.Context, arg CreateAIGroupingReviewCollectionParams) (AiGroupingReviewCollection, error) {
	row := q.queryRow(ctx, q.createAIGroupingReviewCollectionStmt, createAIGroupingReviewCollection,
		arg.ReviewID,
		arg.Name,
		arg.Description,
		arg.SeriesIds,
		arg.SeriesCount,
		arg.Status,
	)
	var i AiGroupingReviewCollection
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.Name,
		&i.Description,
		&i.SeriesIds,
		&i.SeriesCount,
		&i.Status,
		&i.CreatedCollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    series_id, library_id, name, path, size, file_modified_at, 
    volume, title, summary, number, sort_number, page_count, cover_path
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, series_id, library_id, name, path, size, file_modified_at, volume, title, summary, number, sort_number, page_count, cover_path, last_read_page, last_read_at, file_hash, quick_hash, path_fingerprint, path_fingerprint_no_ext, filename_fingerprint, created_at, updated_at
`

type CreateBookParams struct {
	SeriesID       int64           `json:"series_id"`
	LibraryID      int64           `json:"library_id"`
	Name           string          `json:"name"`
	Path           string          `json:"path"`
	Size           int64           `json:"size"`
	FileModifiedAt time.Time       `json:"file_modified_at"`
	Volume         string          `json:"volume"`
	Title          sql.NullString  `json:"title"`
	Summary        sql.NullString  `json:"summary"`
	Number         sql.NullString  `json:"number"`
	SortNumber     sql.NullFloat64 `json:"sort_number"`
	PageCount      int64           `json:"page_count"`
	CoverPath      sql.NullString  `json:"cover_path"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.queryRow(ctx, q.createBookStmt, createBook,
		arg.SeriesID,
		arg.LibraryID,
		arg.Name,
		arg.Path,
		arg.Size,
		arg.FileModifiedAt,
		arg.Volume,
		arg.Title,
		arg.Summary,
		arg.Number,
		arg.SortNumber,
		arg.PageCount,
		arg.CoverPath,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Volume,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CoverPath,
		&i.LastReadPage,
		&i.LastReadAt,
		&i.FileHash,
		&i.QuickHash,
		&i.PathFingerprint,
		&i.PathFingerprintNoExt,
		&i.FilenameFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (name, description)
VALUES (?, ?)
RETURNING id, name, description, cover_url, sort_order, created_at, updated_at
`

type CreateCollectionParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.queryRow(ctx, q.createCollectionStmt, createCollection, arg.Name, arg.Description)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverUrl,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO libraries (name, path, scan_mode, koreader_sync_enabled, scan_interval, scan_formats)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, path, scan_mode, koreader_sync_enabled, scan_interval, scan_formats, created_at
`

type CreateLibraryParams struct {
	Name                string `json:"name"`
	Path                string `json:"path"`
	ScanMode            string `json:"scan_mode"`
	KoreaderSyncEnabled bool   `json:"koreader_sync_enabled"`
	ScanInterval        int64  `json:"scan_interval"`
	ScanFormats         string `json:"scan_formats"`
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.queryRow(ctx, q.createLibraryStmt, createLibrary,
		arg.Name,
		arg.Path,
		arg.ScanMode,
		arg.KoreaderSyncEnabled,
		arg.ScanInterval,
		arg.ScanFormats,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.ScanMode,
		&i.KoreaderSyncEnabled,
		&i.ScanInterval,
		&i.ScanFormats,
		&i.CreatedAt,
	)
	return i, err
}

const createMetadataReview = `-- name: CreateMetadataReview :one
INSERT INTO metadata_reviews (
    series_id, provider, source_url, source_id, source_query, summary, confidence, status, raw_payload
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9
)
RETURNING id, series_id, provider, source_url, source_id, source_query, summary, confidence, status, raw_payload, created_at, updated_at, applied_at, rejected_at
`

type CreateMetadataReviewParams struct {
	SeriesID    int64   `json:"series_id"`
	Provider    string  `json:"provider"`
	SourceUrl   string  `json:"source_url"`
	SourceID    int64   `json:"source_id"`
	SourceQuery string  `json:"source_query"`
	Summary     string  `json:"summary"`
	Confidence  float64 `json:"confidence"`
	Status      string  `json:"status"`
	RawPayload  string  `json:"raw_payload"`
}

func (q *Queries) CreateMetadataReview(ctx context.Context, arg CreateMetadataReviewParams) (MetadataReview, error) {
	row := q.queryRow(ctx, q.createMetadataReviewStmt, createMetadataReview,
		arg.SeriesID,
		arg.Provider,
		arg.SourceUrl,
		arg.SourceID,
		arg.SourceQuery,
		arg.Summary,
		arg.Confidence,
		arg.Status,
		arg.RawPayload,
	)
	var i MetadataReview
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Provider,
		&i.SourceUrl,
		&i.SourceID,
		&i.SourceQuery,
		&i.Summary,
		&i.Confidence,
		&i.Status,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppliedAt,
		&i.RejectedAt,
	)
	return i, err
}

const createMetadataReviewField = `-- name: CreateMetadataReviewField :one
INSERT INTO metadata_review_fields (
    review_id, field_name, current_value, proposed_value, confidence, source, source_url, locked, status
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9
)
RETURNING id, review_id, field_name, current_value, proposed_value, confidence, source, source_url, locked, status, created_at, updated_at
`

type CreateMetadataReviewFieldParams struct {
	ReviewID      int64   `json:"review_id"`
	FieldName     string  `json:"field_name"`
	CurrentValue  string  `json:"current_value"`
	ProposedValue string  `json:"proposed_value"`
	Confidence    float64 `json:"confidence"`
	Source        string  `json:"source"`
	SourceUrl     string  `json:"source_url"`
	Locked        bool    `json:"locked"`
	Status        string  `json:"status"`
}

func (q *Queries) CreateMetadataReviewField(ctx context.Context, arg CreateMetadataReviewFieldParams) (MetadataReviewField, error) {
	row := q.queryRow(ctx, q.createMetadataReviewFieldStmt, createMetadataReviewField,
		arg.ReviewID,
		arg.FieldName,
		arg.CurrentValue,
		arg.ProposedValue,
		arg.Confidence,
		arg.Source,
		arg.SourceUrl,
		arg.Locked,
		arg.Status,
	)
	var i MetadataReviewField
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.FieldName,
		&i.CurrentValue,
		&i.ProposedValue,
		&i.Confidence,
		&i.Source,
		&i.SourceUrl,
		&i.Locked,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReadingList = `-- name: CreateReadingList :one
INSERT INTO reading_lists (name, description)
VALUES (?, ?)
RETURNING id, name, description, sort_order, created_at, updated_at
`

type CreateReadingListParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateReadingList(ctx context.Context, arg CreateReadingListParams) (ReadingList, error) {
	row := q.queryRow(ctx, q.createReadingListStmt, createReadingList, arg.Name, arg.Description)
	var i ReadingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (
    library_id, name, path, title, summary, publisher, status, rating, language, locked_fields, name_initial
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, library_id, name, title, summary, publisher, status, rating, language, locked_fields, name_initial, path, created_at, updated_at, is_favorite, volume_count, book_count, total_pages
`

type CreateSeriesParams struct {
	LibraryID    int64           `json:"library_id"`
	Name         string          `json:"name"`
	Path         string          `json:"path"`
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	NameInitial  string          `json:"name_initial"`
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.queryRow(ctx, q.createSeriesStmt, createSeries,
		arg.LibraryID,
		arg.Name,
		arg.Path,
		arg.Title,
		arg.Summary,
		arg.Publisher,
		arg.Status,
		arg.Rating,
		arg.Language,
		arg.LockedFields,
		arg.NameInitial,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Title,
		&i.Summary,
		&i.Publisher,
		&i.Status,
		&i.Rating,
		&i.Language,
		&i.LockedFields,
		&i.NameInitial,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsFavorite,
		&i.VolumeCount,
		&i.BookCount,
		&i.TotalPages,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteBookStmt, deleteBook, id)
	return err
}

const deleteBookByPath = `-- name: DeleteBookByPath :exec
DELETE FROM books WHERE path = ?
`

func (q *Queries) DeleteBookByPath(ctx context.Context, path string) error {
	_, err := q.exec(ctx, q.deleteBookByPathStmt, deleteBookByPath, path)
	return err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE FROM libraries WHERE id = ?
`

func (q *Queries) DeleteLibrary(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteLibraryStmt, deleteLibrary, id)
	return err
}

const deleteReadingList = `-- name: DeleteReadingList :exec
DELETE FROM reading_lists WHERE id = ?
`

func (q *Queries) DeleteReadingList(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteReadingListStmt, deleteReadingList, id)
	return err
}

const deleteSeries = `-- name: DeleteSeries :exec
DELETE FROM series WHERE id = ?
`

func (q *Queries) DeleteSeries(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteSeriesStmt, deleteSeries, id)
	return err
}

const getAIGroupingReview = `-- name: GetAIGroupingReview :one
SELECT id, library_id, provider, status, summary, raw_payload, candidate_count, collection_count, created_at, updated_at, applied_at, rejected_at FROM ai_grouping_reviews WHERE id = ? LIMIT 1
`

func (q *Queries) GetAIGroupingReview(ctx context.Context, id int64) (AiGroupingReview, error) {
	row := q.queryRow(ctx, q.getAIGroupingReviewStmt, getAIGroupingReview, id)
	var i AiGroupingReview
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Provider,
		&i.Status,
		&i.Summary,
		&i.RawPayload,
		&i.CandidateCount,
		&i.CollectionCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppliedAt,
		&i.RejectedAt,
	)
	return i, err
}

const getAllAuthors = `-- name: GetAllAuthors :many
SELECT id, name, role, created_at FROM authors ORDER BY name
`

func (q *Queries) GetAllAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.query(ctx, q.getAllAuthorsStmt, getAllAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTags = `-- name: GetAllTags :many
SELECT id, name, created_at FROM tags ORDER BY name
`

func (q *Queries) GetAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.query(ctx, q.getAllTagsStmt, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorsForSeries = `-- name: GetAuthorsForSeries :many
SELECT a.id, a.name, a.role, a.created_at FROM authors a
JOIN series_authors sa ON a.id = sa.author_id
WHERE sa.series_id = ? ORDER BY a.role, a.name
`

func (q *Queries) GetAuthorsForSeries(ctx context.Context, seriesID int64) ([]Author, error) {
	rows, err := q.query(ctx, q.getAuthorsForSeriesStmt, getAuthorsForSeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBook = `-- name: GetBook :one
SELECT id, series_id, library_id, name, path, size, file_modified_at, volume, title, summary, number, sort_number, page_count, cover_path, last_read_page, last_read_at, file_hash, quick_hash, path_fingerprint, path_fingerprint_no_ext, filename_fingerprint, created_at, updated_at FROM books WHERE id = ? LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.queryRow(ctx, q.getBookStmt, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Volume,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CoverPath,
		&i.LastReadPage,
		&i.LastReadAt,
		&i.FileHash,
		&i.QuickHash,
		&i.PathFingerprint,
		&i.PathFingerprintNoExt,
		&i.FilenameFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookByPath = `-- name: GetBookByPath :one
SELECT id, series_id, library_id, name, path, size, file_modified_at, volume, title, summary, number, sort_number, page_count, cover_path, last_read_page, last_read_at, file_hash, quick_hash, path_fingerprint, path_fingerprint_no_ext, filename_fingerprint, created_at, updated_at FROM books WHERE path = ? LIMIT 1
`

func (q *Queries) GetBookByPath(ctx context.Context, path string) (Book, error) {
	row := q.queryRow(ctx, q.getBookByPathStmt, getBookByPath, path)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Volume,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CoverPath,
		&i.LastReadPage,
		&i.LastReadAt,
		&i.FileHash,
		&i.QuickHash,
		&i.PathFingerprint,
		&i.PathFingerprintNoExt,
		&i.FilenameFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCandidateSeriesForAI = `-- name: GetCandidateSeriesForAI :many
SELECT s.id, s.title, s.name, s.summary, 
       (SELECT b.cover_path FROM books b WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != '' ORDER BY b.sort_number, b.name LIMIT 1) as cover_path
FROM series s
WHERE s.summary IS NOT NULL AND s.summary != '' 
  AND (s.total_pages = 0 OR (CAST(s.book_count AS REAL) > 0 AND (SELECT COUNT(*) FROM books b WHERE b.series_id = s.id AND b.last_read_page > 0) < s.book_count * 0.5))
ORDER BY RANDOM()
LIMIT ?
`

type GetCandidateSeriesForAIRow struct {
	ID        int64          `json:"id"`
	Title     sql.NullString `json:"title"`
	Name      string         `json:"name"`
	Summary   sql.NullString `json:"summary"`
	CoverPath sql.NullString `json:"cover_path"`
}

func (q *Queries) GetCandidateSeriesForAI(ctx context.Context, limit int64) ([]GetCandidateSeriesForAIRow, error) {
	rows, err := q.query(ctx, q.getCandidateSeriesForAIStmt, getCandidateSeriesForAI, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCandidateSeriesForAIRow
	for rows.Next() {
		var i GetCandidateSeriesForAIRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Name,
			&i.Summary,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, path, scan_mode, koreader_sync_enabled, scan_interval, scan_formats, created_at FROM libraries WHERE id = ? LIMIT 1
`

func (q *Queries) GetLibrary(ctx context.Context, id int64) (Library, error) {
	row := q.queryRow(ctx, q.getLibraryStmt, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.ScanMode,
		&i.KoreaderSyncEnabled,
		&i.ScanInterval,
		&i.ScanFormats,
		&i.CreatedAt,
	)
	return i, err
}

const getLinksForSeries = `-- name: GetLinksForSeries :many
SELECT id, series_id, name, url, created_at FROM series_links WHERE series_id = ? ORDER BY id ASC
`

func (q *Queries) GetLinksForSeries(ctx context.Context, seriesID int64) ([]SeriesLink, error) {
	rows, err := q.query(ctx, q.getLinksForSeriesStmt, getLinksForSeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeriesLink
	for rows.Next() {
		var i SeriesLink
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Name,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetadataReview = `-- name: GetMetadataReview :one
SELECT id, series_id, provider, source_url, source_id, source_query, summary, confidence, status, raw_payload, created_at, updated_at, applied_at, rejected_at FROM metadata_reviews WHERE id = ? LIMIT 1
`

func (q *Queries) GetMetadataReview(ctx context.Context, id int64) (MetadataReview, error) {
	row := q.queryRow(ctx, q.getMetadataReviewStmt, getMetadataReview, id)
	var i MetadataReview
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Provider,
		&i.SourceUrl,
		&i.SourceID,
		&i.SourceQuery,
		&i.Summary,
		&i.Confidence,
		&i.Status,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppliedAt,
		&i.RejectedAt,
	)
	return i, err
}

const getMihonSeries = `-- name: GetMihonSeries :one
SELECT
    s.id,
    s.library_id,
    s.name,
    COALESCE(s.title, '') as title,
    COALESCE(s.summary, '') as summary,
    COALESCE(s.status, '') as status,
    s.updated_at,
    s.book_count,
    s.total_pages,
    CAST(COALESCE((
        SELECT b.id
        FROM books b
        WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != ''
        ORDER BY b.sort_number, b.name
        LIMIT 1
    ), 0) AS INTEGER) as cover_book_id
FROM series s
WHERE s.id = ?
LIMIT 1
`

type GetMihonSeriesRow struct {
	ID          int64     `json:"id"`
	LibraryID   int64     `json:"library_id"`
	Name        string    `json:"name"`
	Title       string    `json:"title"`
	Summary     string    `json:"summary"`
	Status      string    `json:"status"`
	UpdatedAt   time.Time `json:"updated_at"`
	BookCount   int64     `json:"book_count"`
	TotalPages  int64     `json:"total_pages"`
	CoverBookID int64     `json:"cover_book_id"`
}

func (q *Queries) GetMihonSeries(ctx context.Context, id int64) (GetMihonSeriesRow, error) {
	row := q.queryRow(ctx, q.getMihonSeriesStmt, getMihonSeries, id)
	var i GetMihonSeriesRow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Title,
		&i.Summary,
		&i.Status,
		&i.UpdatedAt,
		&i.BookCount,
		&i.TotalPages,
		&i.CoverBookID,
	)
	return i, err
}

const getNextBookInSeries = `-- name: GetNextBookInSeries :one
SELECT nb.id, nb.series_id, nb.library_id, nb.name, nb.path, nb.size, nb.file_modified_at, nb.volume, nb.title, nb.summary, nb.number, nb.sort_number, nb.page_count, nb.cover_path, nb.last_read_page, nb.last_read_at, nb.file_hash, nb.quick_hash, nb.path_fingerprint, nb.path_fingerprint_no_ext, nb.filename_fingerprint, nb.created_at, nb.updated_at FROM books nb
INNER JOIN books cb ON cb.id = ? AND nb.series_id = cb.series_id
WHERE 
   (nb.volume > cb.volume)
   OR (nb.volume = cb.volume AND nb.sort_number > cb.sort_number)
   OR (nb.volume = cb.volume AND nb.sort_number = cb.sort_number AND nb.name > cb.name)
ORDER BY nb.volume ASC, nb.sort_number ASC, nb.name ASC
LIMIT 1
`

func (q *Queries) GetNextBookInSeries(ctx context.Context, id int64) (Book, error) {
	row := q.queryRow(ctx, q.getNextBookInSeriesStmt, getNextBookInSeries, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Volume,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CoverPath,
		&i.LastReadPage,
		&i.LastReadAt,
		&i.FileHash,
		&i.QuickHash,
		&i.PathFingerprint,
		&i.PathFingerprintNoExt,
		&i.FilenameFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReadingList = `-- name: GetReadingList :one
SELECT id, name, description, sort_order, created_at, updated_at FROM reading_lists WHERE id = ? LIMIT 1
`

func (q *Queries) GetReadingList(ctx context.Context, id int64) (ReadingList, error) {
	row := q.queryRow(ctx, q.getReadingListStmt, getReadingList, id)
	var i ReadingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentReadSeries = `-- name: GetRecentReadSeries :many
WITH RankedBooks AS (
    SELECT 
        b.series_id,
        b.id AS book_id,
        b.last_read_at,
        b.last_read_page,
        ROW_NUMBER() OVER(PARTITION BY b.series_id ORDER BY b.last_read_at DESC) as rn
    FROM books b
    WHERE b.last_read_at IS NOT NULL AND b.library_id = ?
)
SELECT 
    s.id, s.library_id, s.name, s.title, s.summary, s.publisher, s.status, s.rating, s.language, s.locked_fields, s.name_initial, s.path, s.created_at, s.updated_at, s.is_favorite, s.volume_count, s.book_count, s.total_pages,
    rb.book_id AS recent_book_id,
    rb.last_read_at,
    rb.last_read_page,
    (SELECT b.cover_path FROM books b WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != '' ORDER BY b.sort_number, b.name LIMIT 1) as cover_path
FROM series s
JOIN RankedBooks rb ON s.id = rb.series_id AND rb.rn = 1
WHERE s.library_id = ?
ORDER BY rb.last_read_at DESC
LIMIT ?
`

type GetRecentReadSeriesParams struct {
	LibraryID   int64 `json:"library_id"`
	LibraryID_2 int64 `json:"library_id_2"`
	Limit       int64 `json:"limit"`
}

type GetRecentReadSeriesRow struct {
	ID           int64           `json:"id"`
	LibraryID    int64           `json:"library_id"`
	Name         string          `json:"name"`
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	NameInitial  string          `json:"name_initial"`
	Path         string          `json:"path"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	IsFavorite   bool            `json:"is_favorite"`
	VolumeCount  int64           `json:"volume_count"`
	BookCount    int64           `json:"book_count"`
	TotalPages   int64           `json:"total_pages"`
	RecentBookID int64           `json:"recent_book_id"`
	LastReadAt   sql.NullTime    `json:"last_read_at"`
	LastReadPage sql.NullInt64   `json:"last_read_page"`
	CoverPath    sql.NullString  `json:"cover_path"`
}

func (q *Queries) GetRecentReadSeries(ctx context.Context, arg GetRecentReadSeriesParams) ([]GetRecentReadSeriesRow, error) {
	rows, err := q.query(ctx, q.getRecentReadSeriesStmt, getRecentReadSeries, arg.LibraryID, arg.LibraryID_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentReadSeriesRow
	for rows.Next() {
		var i GetRecentReadSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Title,
			&i.Summary,
			&i.Publisher,
			&i.Status,
			&i.Rating,
			&i.Language,
			&i.LockedFields,
			&i.NameInitial,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFavorite,
			&i.VolumeCount,
			&i.BookCount,
			&i.TotalPages,
			&i.RecentBookID,
			&i.LastReadAt,
			&i.LastReadPage,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeries = `-- name: GetSeries :one
SELECT id, library_id, name, title, summary, publisher, status, rating, language, locked_fields, name_initial, path, created_at, updated_at, is_favorite, volume_count, book_count, total_pages FROM series WHERE id = ? LIMIT 1
`

func (q *Queries) GetSeries(ctx context.Context, id int64) (Series, error) {
	row := q.queryRow(ctx, q.getSeriesStmt, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Title,
		&i.Summary,
		&i.Publisher,
		&i.Status,
		&i.Rating,
		&i.Language,
		&i.LockedFields,
		&i.NameInitial,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsFavorite,
		&i.VolumeCount,
		&i.BookCount,
		&i.TotalPages,
	)
	return i, err
}

const getSeriesByLibrary = `-- name: GetSeriesByLibrary :many
SELECT
    s.id,
    s.library_id,
    s.name,
    s.title,
    s.summary,
    s.publisher,
    s.status,
    s.rating,
    s.language,
    s.locked_fields,
    s.name_initial,
    s.path,
    s.created_at,
    s.updated_at,
    s.is_favorite,
    s.volume_count,
    s.book_count,
    s.total_pages,
    GROUP_CONCAT(DISTINCT t.name) as tags_string,
    (SELECT b.cover_path FROM books b WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != '' ORDER BY b.sort_number, b.name LIMIT 1) as cover_path,
    (SELECT COUNT(DISTINCT CASE WHEN b.last_read_page > 0 THEN b.id END) FROM books b WHERE b.series_id = s.id) as read_count
FROM series s
LEFT JOIN series_tags st ON s.id = st.series_id
LEFT JOIN tags t ON st.tag_id = t.id
WHERE s.library_id = ? 
GROUP BY s.id
ORDER BY s.name
`

type GetSeriesByLibraryRow struct {
	ID           int64           `json:"id"`
	LibraryID    int64           `json:"library_id"`
	Name         string          `json:"name"`
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	NameInitial  string          `json:"name_initial"`
	Path         string          `json:"path"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	IsFavorite   bool            `json:"is_favorite"`
	VolumeCount  int64           `json:"volume_count"`
	BookCount    int64           `json:"book_count"`
	TotalPages   int64           `json:"total_pages"`
	TagsString   string          `json:"tags_string"`
	CoverPath    sql.NullString  `json:"cover_path"`
	ReadCount    int64           `json:"read_count"`
}

func (q *Queries) GetSeriesByLibrary(ctx context.Context, libraryID int64) ([]GetSeriesByLibraryRow, error) {
	rows, err := q.query(ctx, q.getSeriesByLibraryStmt, getSeriesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeriesByLibraryRow
	for rows.Next() {
		var i GetSeriesByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Title,
			&i.Summary,
			&i.Publisher,
			&i.Status,
			&i.Rating,
			&i.Language,
			&i.LockedFields,
			&i.NameInitial,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFavorite,
			&i.VolumeCount,
			&i.BookCount,
			&i.TotalPages,
			&i.TagsString,
			&i.CoverPath,
			&i.ReadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeriesMetadataProvenance = `-- name: GetSeriesMetadataProvenance :many
SELECT series_id, field_name, value, source, source_url, confidence, review_id, updated_at FROM series_metadata_provenance WHERE series_id = ? ORDER BY field_name
`

func (q *Queries) GetSeriesMetadataProvenance(ctx context.Context, seriesID int64) ([]SeriesMetadataProvenance, error) {
	rows, err := q.query(ctx, q.getSeriesMetadataProvenanceStmt, getSeriesMetadataProvenance, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeriesMetadataProvenance
	for rows.Next() {
		var i SeriesMetadataProvenance
		if err := rows.Scan(
			&i.SeriesID,
			&i.FieldName,
			&i.Value,
			&i.Source,
			&i.SourceUrl,
			&i.Confidence,
			&i.ReviewID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeriesNamesByIDs = `-- name: GetSeriesNamesByIDs :many
SELECT id, name, COALESCE(title, '') as title
FROM series
WHERE id IN (/*SLICE:ids*/?)
ORDER BY COALESCE(NULLIF(title, ''), name) COLLATE NOCASE
`

type GetSeriesNamesByIDsRow struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Title string `json:"title"`
}

func (q *Queries) GetSeriesNamesByIDs(ctx context.Context, ids []int64) ([]GetSeriesNamesByIDsRow, error) {
	query := getSeriesNamesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeriesNamesByIDsRow
	for rows.Next() {
		var i GetSeriesNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeriesWithoutCollection = `-- name: GetSeriesWithoutCollection :many
SELECT s.id, s.title, s.name, s.summary
FROM series s
LEFT JOIN collection_series cs ON s.id = cs.series_id
WHERE s.library_id = ? AND cs.collection_id IS NULL
`

type GetSeriesWithoutCollectionRow struct {
	ID      int64          `json:"id"`
	Title   sql.NullString `json:"title"`
	Name    string         `json:"name"`
	Summary sql.NullString `json:"summary"`
}

func (q *Queries) GetSeriesWithoutCollection(ctx context.Context, libraryID int64) ([]GetSeriesWithoutCollectionRow, error) {
	rows, err := q.query(ctx, q.getSeriesWithoutCollectionStmt, getSeriesWithoutCollection, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeriesWithoutCollectionRow
	for rows.Next() {
		var i GetSeriesWithoutCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Name,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForSeries = `-- name: GetTagsForSeries :many
SELECT t.id, t.name, t.created_at FROM tags t
JOIN series_tags st ON t.id = st.tag_id
WHERE st.series_id = ? ORDER BY t.name
`

func (q *Queries) GetTagsForSeries(ctx context.Context, seriesID int64) ([]Tag, error) {
	rows, err := q.query(ctx, q.getTagsForSeriesStmt, getTagsForSeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopReadingTags = `-- name: GetTopReadingTags :many
SELECT t.name, COUNT(*) as tag_count
FROM tags t
JOIN series_tags st ON t.id = st.tag_id
JOIN books b ON st.series_id = b.series_id
JOIN reading_activity ra ON b.id = ra.book_id
GROUP BY t.id
ORDER BY tag_count DESC
LIMIT ?
`

type GetTopReadingTagsRow struct {
	Name     string `json:"name"`
	TagCount int64  `json:"tag_count"`
}

func (q *Queries) GetTopReadingTags(ctx context.Context, limit int64) ([]GetTopReadingTagsRow, error) {
	rows, err := q.query(ctx, q.getTopReadingTagsStmt, getTopReadingTags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopReadingTagsRow
	for rows.Next() {
		var i GetTopReadingTagsRow
		if err := rows.Scan(&i.Name, &i.TagCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSeriesAuthor = `-- name: LinkSeriesAuthor :exec
INSERT OR IGNORE INTO series_authors (series_id, author_id) VALUES (?, ?)
`

type LinkSeriesAuthorParams struct {
	SeriesID int64 `json:"series_id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) LinkSeriesAuthor(ctx context.Context, arg LinkSeriesAuthorParams) error {
	_, err := q.exec(ctx, q.linkSeriesAuthorStmt, linkSeriesAuthor, arg.SeriesID, arg.AuthorID)
	return err
}

const linkSeriesLink = `-- name: LinkSeriesLink :one
INSERT INTO series_links (series_id, name, url) VALUES (?, ?, ?)
RETURNING id, series_id, name, url, created_at
`

type LinkSeriesLinkParams struct {
	SeriesID int64  `json:"series_id"`
	Name     string `json:"name"`
	Url      string `json:"url"`
}

func (q *Queries) LinkSeriesLink(ctx context.Context, arg LinkSeriesLinkParams) (SeriesLink, error) {
	row := q.queryRow(ctx, q.linkSeriesLinkStmt, linkSeriesLink, arg.SeriesID, arg.Name, arg.Url)
	var i SeriesLink
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const linkSeriesTag = `-- name: LinkSeriesTag :exec
INSERT OR IGNORE INTO series_tags (series_id, tag_id) VALUES (?, ?)
`

type LinkSeriesTagParams struct {
	SeriesID int64 `json:"series_id"`
	TagID    int64 `json:"tag_id"`
}

func (q *Queries) LinkSeriesTag(ctx context.Context, arg LinkSeriesTagParams) error {
	_, err := q.exec(ctx, q.linkSeriesTagStmt, linkSeriesTag, arg.SeriesID, arg.TagID)
	return err
}

const listAIGroupingReviewCollections = `-- name: ListAIGroupingReviewCollections :many
SELECT id, review_id, name, description, series_ids, series_count, status, created_collection_id, created_at, updated_at FROM ai_grouping_review_collections WHERE review_id = ? ORDER BY id ASC
`

func (q *Queries) ListAIGroupingReviewCollections(ctx context.Context, reviewID int64) ([]AiGroupingReviewCollection, error) {
	rows, err := q.query(ctx, q.listAIGroupingReviewCollectionsStmt, listAIGroupingReviewCollections, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiGroupingReviewCollection
	for rows.Next() {
		var i AiGroupingReviewCollection
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.Name,
			&i.Description,
			&i.SeriesIds,
			&i.SeriesCount,
			&i.Status,
			&i.CreatedCollectionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIGroupingReviews = `-- name: ListAIGroupingReviews :many
SELECT
    agr.id,
    agr.library_id,
    l.name as library_name,
    agr.provider,
    agr.status,
    agr.summary,
    agr.raw_payload,
    agr.candidate_count,
    agr.collection_count,
    agr.created_at,
    agr.updated_at,
    agr.applied_at,
    agr.rejected_at
FROM ai_grouping_reviews agr
JOIN libraries l ON l.id = agr.library_id
WHERE (CAST(?1 AS INTEGER) = 0 OR agr.library_id = CAST(?1 AS INTEGER))
  AND (CAST(?2 AS TEXT) = '' OR agr.status = CAST(?2 AS TEXT))
ORDER BY agr.created_at DESC
LIMIT ?4 OFFSET ?3
`

type ListAIGroupingReviewsParams struct {
	LibraryID int64  `json:"library_id"`
	Status    string `json:"status"`
	Offset    int64  `json:"offset"`
	Limit     int64  `json:"limit"`
}

type ListAIGroupingReviewsRow struct {
	ID              int64        `json:"id"`
	LibraryID       int64        `json:"library_id"`
	LibraryName     string       `json:"library_name"`
	Provider        string       `json:"provider"`
	Status          string       `json:"status"`
	Summary         string       `json:"summary"`
	RawPayload      string       `json:"raw_payload"`
	CandidateCount  int64        `json:"candidate_count"`
	CollectionCount int64        `json:"collection_count"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	AppliedAt       sql.NullTime `json:"applied_at"`
	RejectedAt      sql.NullTime `json:"rejected_at"`
}

func (q *Queries) ListAIGroupingReviews(ctx context.Context, arg ListAIGroupingReviewsParams) ([]ListAIGroupingReviewsRow, error) {
	rows, err := q.query(ctx, q.listAIGroupingReviewsStmt, listAIGroupingReviews,
		arg.LibraryID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIGroupingReviewsRow
	for rows.Next() {
		var i ListAIGroupingReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.LibraryName,
			&i.Provider,
			&i.Status,
			&i.Summary,
			&i.RawPayload,
			&i.CandidateCount,
			&i.CollectionCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppliedAt,
			&i.RejectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksByLibrary = `-- name: ListBooksByLibrary :many
SELECT id, path, file_modified_at, size, cover_path FROM books WHERE library_id = ?
`

type ListBooksByLibraryRow struct {
	ID             int64          `json:"id"`
	Path           string         `json:"path"`
	FileModifiedAt time.Time      `json:"file_modified_at"`
	Size           int64          `json:"size"`
	CoverPath      sql.NullString `json:"cover_path"`
}

func (q *Queries) ListBooksByLibrary(ctx context.Context, libraryID int64) ([]ListBooksByLibraryRow, error) {
	rows, err := q.query(ctx, q.listBooksByLibraryStmt, listBooksByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksByLibraryRow
	for rows.Next() {
		var i ListBooksByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FileModifiedAt,
			&i.Size,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksBySeries = `-- name: ListBooksBySeries :many
SELECT id, series_id, library_id, name, path, size, file_modified_at, volume, title, summary, number, sort_number, page_count, cover_path, last_read_page, last_read_at, file_hash, quick_hash, path_fingerprint, path_fingerprint_no_ext, filename_fingerprint, created_at, updated_at FROM books WHERE series_id = ? ORDER BY volume, sort_number, name
`

func (q *Queries) ListBooksBySeries(ctx context.Context, seriesID int64) ([]Book, error) {
	rows, err := q.query(ctx, q.listBooksBySeriesStmt, listBooksBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.LibraryID,
			&i.Name,
			&i.Path,
			&i.Size,
			&i.FileModifiedAt,
			&i.Volume,
			&i.Title,
			&i.Summary,
			&i.Number,
			&i.SortNumber,
			&i.PageCount,
			&i.CoverPath,
			&i.LastReadPage,
			&i.LastReadAt,
			&i.FileHash,
			&i.QuickHash,
			&i.PathFingerprint,
			&i.PathFingerprintNoExt,
			&i.FilenameFingerprint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, path, scan_mode, koreader_sync_enabled, scan_interval, scan_formats, created_at FROM libraries ORDER BY name
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.query(ctx, q.listLibrariesStmt, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.ScanMode,
			&i.KoreaderSyncEnabled,
			&i.ScanInterval,
			&i.ScanFormats,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetadataReviewFields = `-- name: ListMetadataReviewFields :many
SELECT id, review_id, field_name, current_value, proposed_value, confidence, source, source_url, locked, status, created_at, updated_at FROM metadata_review_fields WHERE review_id = ? ORDER BY id ASC
`

func (q *Queries) ListMetadataReviewFields(ctx context.Context, reviewID int64) ([]MetadataReviewField, error) {
	rows, err := q.query(ctx, q.listMetadataReviewFieldsStmt, listMetadataReviewFields, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetadataReviewField
	for rows.Next() {
		var i MetadataReviewField
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.FieldName,
			&i.CurrentValue,
			&i.ProposedValue,
			&i.Confidence,
			&i.Source,
			&i.SourceUrl,
			&i.Locked,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetadataReviewsBySeries = `-- name: ListMetadataReviewsBySeries :many
SELECT id, series_id, provider, source_url, source_id, source_query, summary, confidence, status, raw_payload, created_at, updated_at, applied_at, rejected_at FROM metadata_reviews WHERE series_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListMetadataReviewsBySeries(ctx context.Context, seriesID int64) ([]MetadataReview, error) {
	rows, err := q.query(ctx, q.listMetadataReviewsBySeriesStmt, listMetadataReviewsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetadataReview
	for rows.Next() {
		var i MetadataReview
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Provider,
			&i.SourceUrl,
			&i.SourceID,
			&i.SourceQuery,
			&i.Summary,
			&i.Confidence,
			&i.Status,
			&i.RawPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppliedAt,
			&i.RejectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMihonSeries = `-- name: ListMihonSeries :many
SELECT
    s.id,
    s.library_id,
    s.name,
    COALESCE(s.title, '') as title,
    COALESCE(s.summary, '') as summary,
    COALESCE(s.status, '') as status,
    s.updated_at,
    s.book_count,
    s.total_pages,
    CAST(COALESCE((
        SELECT b.id
        FROM books b
        WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != ''
        ORDER BY b.sort_number, b.name
        LIMIT 1
    ), 0) AS INTEGER) as cover_book_id
FROM series s
WHERE (CAST(?1 AS INTEGER) = 0 OR s.library_id = CAST(?1 AS INTEGER))
  AND (
    CAST(?2 AS TEXT) = ''
    OR instr(lower(s.name), lower(CAST(?2 AS TEXT))) > 0
    OR instr(lower(COALESCE(s.title, '')), lower(CAST(?2 AS TEXT))) > 0
  )
ORDER BY COALESCE(NULLIF(s.title, ''), s.name) COLLATE NOCASE ASC
LIMIT ?4 OFFSET ?3
`

type ListMihonSeriesParams struct {
	LibraryID int64  `json:"library_id"`
	Query     string `json:"query"`
	Offset    int64  `json:"offset"`
	Limit     int64  `json:"limit"`
}

type ListMihonSeriesRow struct {
	ID          int64     `json:"id"`
	LibraryID   int64     `json:"library_id"`
	Name        string    `json:"name"`
	Title       string    `json:"title"`
	Summary     string    `json:"summary"`
	Status      string    `json:"status"`
	UpdatedAt   time.Time `json:"updated_at"`
	BookCount   int64     `json:"book_count"`
	TotalPages  int64     `json:"total_pages"`
	CoverBookID int64     `json:"cover_book_id"`
}

func (q *Queries) ListMihonSeries(ctx context.Context, arg ListMihonSeriesParams) ([]ListMihonSeriesRow, error) {
	rows, err := q.query(ctx, q.listMihonSeriesStmt, listMihonSeries,
		arg.LibraryID,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMihonSeriesRow
	for rows.Next() {
		var i ListMihonSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Title,
			&i.Summary,
			&i.Status,
			&i.UpdatedAt,
			&i.BookCount,
			&i.TotalPages,
			&i.CoverBookID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMihonSeriesByBooks = `-- name: ListMihonSeriesByBooks :many
SELECT
    s.id,
    s.library_id,
    s.name,
    COALESCE(s.title, '') as title,
    COALESCE(s.summary, '') as summary,
    COALESCE(s.status, '') as status,
    s.updated_at,
    s.book_count,
    s.total_pages,
    CAST(COALESCE((
        SELECT b.id
        FROM books b
        WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != ''
        ORDER BY b.sort_number, b.name
        LIMIT 1
    ), 0) AS INTEGER) as cover_book_id
FROM series s
WHERE (CAST(?1 AS INTEGER) = 0 OR s.library_id = CAST(?1 AS INTEGER))
  AND (
    CAST(?2 AS TEXT) = ''
    OR instr(lower(s.name), lower(CAST(?2 AS TEXT))) > 0
    OR instr(lower(COALESCE(s.title, '')), lower(CAST(?2 AS TEXT))) > 0
  )
ORDER BY s.book_count DESC, COALESCE(NULLIF(s.title, ''), s.name) COLLATE NOCASE ASC
LIMIT ?4 OFFSET ?3
`

type ListMihonSeriesByBooksParams struct {
	LibraryID int64  `json:"library_id"`
	Query     string `json:"query"`
	Offset    int64  `json:"offset"`
	Limit     int64  `json:"limit"`
}

type ListMihonSeriesByBooksRow struct {
	ID          int64     `json:"id"`
	LibraryID   int64     `json:"library_id"`
	Name        string    `json:"name"`
	Title       string    `json:"title"`
	Summary     string    `json:"summary"`
	Status      string    `json:"status"`
	UpdatedAt   time.Time `json:"updated_at"`
	BookCount   int64     `json:"book_count"`
	TotalPages  int64     `json:"total_pages"`
	CoverBookID int64     `json:"cover_book_id"`
}

func (q *Queries) ListMihonSeriesByBooks(ctx context.Context, arg ListMihonSeriesByBooksParams) ([]ListMihonSeriesByBooksRow, error) {
	rows, err := q.query(ctx, q.listMihonSeriesByBooksStmt, listMihonSeriesByBooks,
		arg.LibraryID,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMihonSeriesByBooksRow
	for rows.Next() {
		var i ListMihonSeriesByBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Title,
			&i.Summary,
			&i.Status,
			&i.UpdatedAt,
			&i.BookCount,
			&i.TotalPages,
			&i.CoverBookID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMihonSeriesByUpdated = `-- name: ListMihonSeriesByUpdated :many
SELECT
    s.id,
    s.library_id,
    s.name,
    COALESCE(s.title, '') as title,
    COALESCE(s.summary, '') as summary,
    COALESCE(s.status, '') as status,
    s.updated_at,
    s.book_count,
    s.total_pages,
    CAST(COALESCE((
        SELECT b.id
        FROM books b
        WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != ''
        ORDER BY b.sort_number, b.name
        LIMIT 1
    ), 0) AS INTEGER) as cover_book_id
FROM series s
WHERE (CAST(?1 AS INTEGER) = 0 OR s.library_id = CAST(?1 AS INTEGER))
  AND (
    CAST(?2 AS TEXT) = ''
    OR instr(lower(s.name), lower(CAST(?2 AS TEXT))) > 0
    OR instr(lower(COALESCE(s.title, '')), lower(CAST(?2 AS TEXT))) > 0
  )
ORDER BY s.updated_at DESC, COALESCE(NULLIF(s.title, ''), s.name) COLLATE NOCASE ASC
LIMIT ?4 OFFSET ?3
`

type ListMihonSeriesByUpdatedParams struct {
	LibraryID int64  `json:"library_id"`
	Query     string `json:"query"`
	Offset    int64  `json:"offset"`
	Limit     int64  `json:"limit"`
}

type ListMihonSeriesByUpdatedRow struct {
	ID          int64     `json:"id"`
	LibraryID   int64     `json:"library_id"`
	Name        string    `json:"name"`
	Title       string    `json:"title"`
	Summary     string    `json:"summary"`
	Status      string    `json:"status"`
	UpdatedAt   time.Time `json:"updated_at"`
	BookCount   int64     `json:"book_count"`
	TotalPages  int64     `json:"total_pages"`
	CoverBookID int64     `json:"cover_book_id"`
}

func (q *Queries) ListMihonSeriesByUpdated(ctx context.Context, arg ListMihonSeriesByUpdatedParams) ([]ListMihonSeriesByUpdatedRow, error) {
	rows, err := q.query(ctx, q.listMihonSeriesByUpdatedStmt, listMihonSeriesByUpdated,
		arg.LibraryID,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMihonSeriesByUpdatedRow
	for rows.Next() {
		var i ListMihonSeriesByUpdatedRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Title,
			&i.Summary,
			&i.Status,
			&i.UpdatedAt,
			&i.BookCount,
			&i.TotalPages,
			&i.CoverBookID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMetadataReviewInbox = `-- name: ListPendingMetadataReviewInbox :many
SELECT
    mr.id,
    mr.series_id,
    mr.provider,
    mr.source_url,
    mr.source_id,
    mr.source_query,
    mr.summary,
    mr.confidence,
    mr.status,
    mr.raw_payload,
    mr.created_at,
    mr.updated_at,
    mr.applied_at,
    mr.rejected_at,
    s.library_id,
    l.name as library_name,
    s.name as series_name,
    COALESCE(s.title, '') as series_title,
    CAST(COALESCE((
        SELECT b.id
        FROM books b
        WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != ''
        ORDER BY b.sort_number, b.name
        LIMIT 1
    ), 0) AS INTEGER) as cover_book_id,
    CAST((SELECT COUNT(*) FROM metadata_review_fields f WHERE f.review_id = mr.id) AS INTEGER) as field_count,
    CAST((SELECT COUNT(*) FROM metadata_review_fields f WHERE f.review_id = mr.id AND f.locked = TRUE) AS INTEGER) as locked_field_count
FROM metadata_reviews mr
JOIN series s ON s.id = mr.series_id
JOIN libraries l ON l.id = s.library_id
WHERE mr.status = 'pending'
  AND (CAST(?1 AS INTEGER) = 0 OR s.library_id = CAST(?1 AS INTEGER))
  AND (CAST(?2 AS TEXT) = '' OR lower(mr.provider) = lower(CAST(?2 AS TEXT)))
  AND (
    CAST(?3 AS TEXT) = ''
    OR instr(lower(s.name), lower(CAST(?3 AS TEXT))) > 0
    OR instr(lower(COALESCE(s.title, '')), lower(CAST(?3 AS TEXT))) > 0
    OR instr(lower(mr.source_query), lower(CAST(?3 AS TEXT))) > 0
  )
ORDER BY mr.confidence ASC, mr.created_at ASC
LIMIT ?5 OFFSET ?4
`

type ListPendingMetadataReviewInboxParams struct {
	LibraryID int64  `json:"library_id"`
	Provider  string `json:"provider"`
	Query     string `json:"query"`
	Offset    int64  `json:"offset"`
	Limit     int64  `json:"limit"`
}

type ListPendingMetadataReviewInboxRow struct {
	ID               int64        `json:"id"`
	SeriesID         int64        `json:"series_id"`
	Provider         string       `json:"provider"`
	SourceUrl        string       `json:"source_url"`
	SourceID         int64        `json:"source_id"`
	SourceQuery      string       `json:"source_query"`
	Summary          string       `json:"summary"`
	Confidence       float64      `json:"confidence"`
	Status           string       `json:"status"`
	RawPayload       string       `json:"raw_payload"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	AppliedAt        sql.NullTime `json:"applied_at"`
	RejectedAt       sql.NullTime `json:"rejected_at"`
	LibraryID        int64        `json:"library_id"`
	LibraryName      string       `json:"library_name"`
	SeriesName       string       `json:"series_name"`
	SeriesTitle      string       `json:"series_title"`
	CoverBookID      int64        `json:"cover_book_id"`
	FieldCount       int64        `json:"field_count"`
	LockedFieldCount int64        `json:"locked_field_count"`
}

func (q *Queries) ListPendingMetadataReviewInbox(ctx context.Context, arg ListPendingMetadataReviewInboxParams) ([]ListPendingMetadataReviewInboxRow, error) {
	rows, err := q.query(ctx, q.listPendingMetadataReviewInboxStmt, listPendingMetadataReviewInbox,
		arg.LibraryID,
		arg.Provider,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingMetadataReviewInboxRow
	for rows.Next() {
		var i ListPendingMetadataReviewInboxRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Provider,
			&i.SourceUrl,
			&i.SourceID,
			&i.SourceQuery,
			&i.Summary,
			&i.Confidence,
			&i.Status,
			&i.RawPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppliedAt,
			&i.RejectedAt,
			&i.LibraryID,
			&i.LibraryName,
			&i.SeriesName,
			&i.SeriesTitle,
			&i.CoverBookID,
			&i.FieldCount,
			&i.LockedFieldCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMetadataReviewsBySeries = `-- name: ListPendingMetadataReviewsBySeries :many
SELECT id, series_id, provider, source_url, source_id, source_query, summary, confidence, status, raw_payload, created_at, updated_at, applied_at, rejected_at FROM metadata_reviews WHERE series_id = ? AND status = 'pending' ORDER BY confidence DESC, created_at DESC
`

func (q *Queries) ListPendingMetadataReviewsBySeries(ctx context.Context, seriesID int64) ([]MetadataReview, error) {
	rows, err := q.query(ctx, q.listPendingMetadataReviewsBySeriesStmt, listPendingMetadataReviewsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetadataReview
	for rows.Next() {
		var i MetadataReview
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Provider,
			&i.SourceUrl,
			&i.SourceID,
			&i.SourceQuery,
			&i.Summary,
			&i.Confidence,
			&i.Status,
			&i.RawPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppliedAt,
			&i.RejectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingListItems = `-- name: ListReadingListItems :many
SELECT
    rli.id,
    rli.reading_list_id,
    rli.series_id,
    rli.sort_order,
    rli.note,
    rli.created_at,
    rli.updated_at,
    s.name as series_name,
    COALESCE(s.title, '') as series_title,
    s.book_count,
    CAST(COALESCE((
        SELECT b.cover_path
        FROM books b
        WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != ''
        ORDER BY b.sort_number, b.name
        LIMIT 1
    ), '') AS TEXT) as cover_path,
    CAST(COALESCE((
        SELECT b.id
        FROM books b
        WHERE b.series_id = s.id
        ORDER BY
            CASE
                WHEN b.page_count = 0 THEN 0
                WHEN b.last_read_page IS NULL THEN 0
                WHEN b.last_read_page < b.page_count THEN 0
                ELSE 1
            END,
            b.sort_number,
            b.name
        LIMIT 1
    ), 0) AS INTEGER) as next_book_id
FROM reading_list_items rli
JOIN series s ON s.id = rli.series_id
WHERE rli.reading_list_id = ?
ORDER BY rli.sort_order, s.name
`

type ListReadingListItemsRow struct {
	ID            int64     `json:"id"`
	ReadingListID int64     `json:"reading_list_id"`
	SeriesID      int64     `json:"series_id"`
	SortOrder     int64     `json:"sort_order"`
	Note          string    `json:"note"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	SeriesName    string    `json:"series_name"`
	SeriesTitle   string    `json:"series_title"`
	BookCount     int64     `json:"book_count"`
	CoverPath     string    `json:"cover_path"`
	NextBookID    int64     `json:"next_book_id"`
}

func (q *Queries) ListReadingListItems(ctx context.Context, readingListID int64) ([]ListReadingListItemsRow, error) {
	rows, err := q.query(ctx, q.listReadingListItemsStmt, listReadingListItems, readingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadingListItemsRow
	for rows.Next() {
		var i ListReadingListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReadingListID,
			&i.SeriesID,
			&i.SortOrder,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SeriesName,
			&i.SeriesTitle,
			&i.BookCount,
			&i.CoverPath,
			&i.NextBookID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingLists = `-- name: ListReadingLists :many
SELECT
    rl.id,
    rl.name,
    rl.description,
    rl.sort_order,
    rl.created_at,
    rl.updated_at,
    COUNT(rli.id) as item_count
FROM reading_lists rl
LEFT JOIN reading_list_items rli ON rli.reading_list_id = rl.id
GROUP BY rl.id
ORDER BY rl.sort_order, rl.name
`

type ListReadingListsRow struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	SortOrder   int64     `json:"sort_order"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ItemCount   int64     `json:"item_count"`
}

func (q *Queries) ListReadingLists(ctx context.Context) ([]ListReadingListsRow, error) {
	rows, err := q.query(ctx, q.listReadingListsStmt, listReadingLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadingListsRow
	for rows.Next() {
		var i ListReadingListsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesByLibrary = `-- name: ListSeriesByLibrary :many
SELECT
       s.id,
       s.library_id,
       s.name,
       s.title,
       s.summary,
       s.publisher,
       s.status,
       s.rating,
       s.language,
       s.locked_fields,
       s.name_initial,
       s.path,
       s.created_at,
       s.updated_at,
       s.is_favorite,
       s.volume_count,
       s.book_count,
       s.total_pages,
       (SELECT b.cover_path 
        FROM books b 
        WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != ''
        ORDER BY b.sort_number, b.name 
        LIMIT 1) as cover_path 
FROM series s 
WHERE s.library_id = ? 
ORDER BY s.name
`

type ListSeriesByLibraryRow struct {
	ID           int64           `json:"id"`
	LibraryID    int64           `json:"library_id"`
	Name         string          `json:"name"`
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	NameInitial  string          `json:"name_initial"`
	Path         string          `json:"path"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	IsFavorite   bool            `json:"is_favorite"`
	VolumeCount  int64           `json:"volume_count"`
	BookCount    int64           `json:"book_count"`
	TotalPages   int64           `json:"total_pages"`
	CoverPath    sql.NullString  `json:"cover_path"`
}

func (q *Queries) ListSeriesByLibrary(ctx context.Context, libraryID int64) ([]ListSeriesByLibraryRow, error) {
	rows, err := q.query(ctx, q.listSeriesByLibraryStmt, listSeriesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesByLibraryRow
	for rows.Next() {
		var i ListSeriesByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Title,
			&i.Summary,
			&i.Publisher,
			&i.Status,
			&i.Rating,
			&i.Language,
			&i.LockedFields,
			&i.NameInitial,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFavorite,
			&i.VolumeCount,
			&i.BookCount,
			&i.TotalPages,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesInitialBackfillCandidates = `-- name: ListSeriesInitialBackfillCandidates :many
SELECT id, name, title, name_initial FROM series
`

type ListSeriesInitialBackfillCandidatesRow struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Title       sql.NullString `json:"title"`
	NameInitial string         `json:"name_initial"`
}

func (q *Queries) ListSeriesInitialBackfillCandidates(ctx context.Context) ([]ListSeriesInitialBackfillCandidatesRow, error) {
	rows, err := q.query(ctx, q.listSeriesInitialBackfillCandidatesStmt, listSeriesInitialBackfillCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesInitialBackfillCandidatesRow
	for rows.Next() {
		var i ListSeriesInitialBackfillCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.NameInitial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAIGroupingReviewCollectionApplied = `-- name: MarkAIGroupingReviewCollectionApplied :exec
UPDATE ai_grouping_review_collections
SET status = 'applied',
    created_collection_id = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type MarkAIGroupingReviewCollectionAppliedParams struct {
	CreatedCollectionID sql.NullInt64 `json:"created_collection_id"`
	ID                  int64         `json:"id"`
}

func (q *Queries) MarkAIGroupingReviewCollectionApplied(ctx context.Context, arg MarkAIGroupingReviewCollectionAppliedParams) error {
	_, err := q.exec(ctx, q.markAIGroupingReviewCollectionAppliedStmt, markAIGroupingReviewCollectionApplied, arg.CreatedCollectionID, arg.ID)
	return err
}

const markAIGroupingReviewCollectionsRejected = `-- name: MarkAIGroupingReviewCollectionsRejected :exec
UPDATE ai_grouping_review_collections
SET status = 'rejected',
    updated_at = CURRENT_TIMESTAMP
WHERE review_id = ?1
  AND status = 'pending'
`

func (q *Queries) MarkAIGroupingReviewCollectionsRejected(ctx context.Context, reviewID int64) error {
	_, err := q.exec(ctx, q.markAIGroupingReviewCollectionsRejectedStmt, markAIGroupingReviewCollectionsRejected, reviewID)
	return err
}

const removeReadingListItem = `-- name: RemoveReadingListItem :exec
DELETE FROM reading_list_items WHERE reading_list_id = ? AND id = ?
`

type RemoveReadingListItemParams struct {
	ReadingListID int64 `json:"reading_list_id"`
	ID            int64 `json:"id"`
}

func (q *Queries) RemoveReadingListItem(ctx context.Context, arg RemoveReadingListItemParams) error {
	_, err := q.exec(ctx, q.removeReadingListItemStmt, removeReadingListItem, arg.ReadingListID, arg.ID)
	return err
}

const searchOPDSSeries = `-- name: SearchOPDSSeries :many
SELECT
    s.id,
    s.name,
    COALESCE(s.title, '') as title,
    COALESCE(s.summary, '') as summary,
    s.updated_at,
    CAST(COALESCE((
        SELECT b.cover_path
        FROM books b
        WHERE b.series_id = s.id AND b.cover_path IS NOT NULL AND b.cover_path != ''
        ORDER BY b.sort_number, b.name
        LIMIT 1
    ), '') AS TEXT) as cover_path
FROM series s
WHERE instr(lower(s.name), lower(?1)) > 0
   OR instr(lower(COALESCE(s.title, '')), lower(?1)) > 0
ORDER BY COALESCE(NULLIF(s.title, ''), s.name) COLLATE NOCASE
LIMIT ?3 OFFSET ?2
`

type SearchOPDSSeriesParams struct {
	Query  string `json:"query"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type SearchOPDSSeriesRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Title     string    `json:"title"`
	Summary   string    `json:"summary"`
	UpdatedAt time.Time `json:"updated_at"`
	CoverPath string    `json:"cover_path"`
}

func (q *Queries) SearchOPDSSeries(ctx context.Context, arg SearchOPDSSeriesParams) ([]SearchOPDSSeriesRow, error) {
	rows, err := q.query(ctx, q.searchOPDSSeriesStmt, searchOPDSSeries, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchOPDSSeriesRow
	for rows.Next() {
		var i SearchOPDSSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Summary,
			&i.UpdatedAt,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchCollection = `-- name: TouchCollection :exec
UPDATE collections
SET updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) TouchCollection(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.touchCollectionStmt, touchCollection, id)
	return err
}

const updateAIGroupingReviewStatus = `-- name: UpdateAIGroupingReviewStatus :one
UPDATE ai_grouping_reviews
SET status = ?1,
    updated_at = CURRENT_TIMESTAMP,
    applied_at = CASE WHEN ?1 = 'applied' THEN CURRENT_TIMESTAMP ELSE applied_at END,
    rejected_at = CASE WHEN ?1 = 'rejected' THEN CURRENT_TIMESTAMP ELSE rejected_at END
WHERE id = ?2
RETURNING id, library_id, provider, status, summary, raw_payload, candidate_count, collection_count, created_at, updated_at, applied_at, rejected_at
`

type UpdateAIGroupingReviewStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateAIGroupingReviewStatus(ctx context.Context, arg UpdateAIGroupingReviewStatusParams) (AiGroupingReview, error) {
	row := q.queryRow(ctx, q.updateAIGroupingReviewStatusStmt, updateAIGroupingReviewStatus, arg.Status, arg.ID)
	var i AiGroupingReview
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Provider,
		&i.Status,
		&i.Summary,
		&i.RawPayload,
		&i.CandidateCount,
		&i.CollectionCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppliedAt,
		&i.RejectedAt,
	)
	return i, err
}

const updateBookProgress = `-- name: UpdateBookProgress :exec
UPDATE books 
SET last_read_page = ?, last_read_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateBookProgressParams struct {
	LastReadPage sql.NullInt64 `json:"last_read_page"`
	LastReadAt   sql.NullTime  `json:"last_read_at"`
	ID           int64         `json:"id"`
}

func (q *Queries) UpdateBookProgress(ctx context.Context, arg UpdateBookProgressParams) error {
	_, err := q.exec(ctx, q.updateBookProgressStmt, updateBookProgress, arg.LastReadPage, arg.LastReadAt, arg.ID)
	return err
}

const updateLibrary = `-- name: UpdateLibrary :one
UPDATE libraries
SET name = ?, path = ?, scan_mode = ?, koreader_sync_enabled = ?, scan_interval = ?, scan_formats = ?
WHERE id = ?
RETURNING id, name, path, scan_mode, koreader_sync_enabled, scan_interval, scan_formats, created_at
`

type UpdateLibraryParams struct {
	Name                string `json:"name"`
	Path                string `json:"path"`
	ScanMode            string `json:"scan_mode"`
	KoreaderSyncEnabled bool   `json:"koreader_sync_enabled"`
	ScanInterval        int64  `json:"scan_interval"`
	ScanFormats         string `json:"scan_formats"`
	ID                  int64  `json:"id"`
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error) {
	row := q.queryRow(ctx, q.updateLibraryStmt, updateLibrary,
		arg.Name,
		arg.Path,
		arg.ScanMode,
		arg.KoreaderSyncEnabled,
		arg.ScanInterval,
		arg.ScanFormats,
		arg.ID,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.ScanMode,
		&i.KoreaderSyncEnabled,
		&i.ScanInterval,
		&i.ScanFormats,
		&i.CreatedAt,
	)
	return i, err
}

const updateMetadataReviewStatus = `-- name: UpdateMetadataReviewStatus :one
UPDATE metadata_reviews
SET status = ?1,
    updated_at = CURRENT_TIMESTAMP,
    applied_at = CASE WHEN ?1 = 'applied' THEN CURRENT_TIMESTAMP ELSE applied_at END,
    rejected_at = CASE WHEN ?1 = 'rejected' THEN CURRENT_TIMESTAMP ELSE rejected_at END
WHERE id = ?2
RETURNING id, series_id, provider, source_url, source_id, source_query, summary, confidence, status, raw_payload, created_at, updated_at, applied_at, rejected_at
`

type UpdateMetadataReviewStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateMetadataReviewStatus(ctx context.Context, arg UpdateMetadataReviewStatusParams) (MetadataReview, error) {
	row := q.queryRow(ctx, q.updateMetadataReviewStatusStmt, updateMetadataReviewStatus, arg.Status, arg.ID)
	var i MetadataReview
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Provider,
		&i.SourceUrl,
		&i.SourceID,
		&i.SourceQuery,
		&i.Summary,
		&i.Confidence,
		&i.Status,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppliedAt,
		&i.RejectedAt,
	)
	return i, err
}

const updateReadingList = `-- name: UpdateReadingList :one
UPDATE reading_lists
SET name = ?, description = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, sort_order, created_at, updated_at
`

type UpdateReadingListParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateReadingList(ctx context.Context, arg UpdateReadingListParams) (ReadingList, error) {
	row := q.queryRow(ctx, q.updateReadingListStmt, updateReadingList, arg.Name, arg.Description, arg.ID)
	var i ReadingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReadingListItemSortOrder = `-- name: UpdateReadingListItemSortOrder :exec
UPDATE reading_list_items
SET sort_order = ?, updated_at = CURRENT_TIMESTAMP
WHERE reading_list_id = ? AND id = ?
`

type UpdateReadingListItemSortOrderParams struct {
	SortOrder     int64 `json:"sort_order"`
	ReadingListID int64 `json:"reading_list_id"`
	ID            int64 `json:"id"`
}

func (q *Queries) UpdateReadingListItemSortOrder(ctx context.Context, arg UpdateReadingListItemSortOrderParams) error {
	_, err := q.exec(ctx, q.updateReadingListItemSortOrderStmt, updateReadingListItemSortOrder, arg.SortOrder, arg.ReadingListID, arg.ID)
	return err
}

const updateSeriesFavorite = `-- name: UpdateSeriesFavorite :exec
UPDATE series SET is_favorite = ? WHERE id = ?
`

type UpdateSeriesFavoriteParams struct {
	IsFavorite bool  `json:"is_favorite"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateSeriesFavorite(ctx context.Context, arg UpdateSeriesFavoriteParams) error {
	_, err := q.exec(ctx, q.updateSeriesFavoriteStmt, updateSeriesFavorite, arg.IsFavorite, arg.ID)
	return err
}

const updateSeriesInitial = `-- name: UpdateSeriesInitial :exec
UPDATE series SET name_initial = ? WHERE id = ?
`

type UpdateSeriesInitialParams struct {
	NameInitial string `json:"name_initial"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateSeriesInitial(ctx context.Context, arg UpdateSeriesInitialParams) error {
	_, err := q.exec(ctx, q.updateSeriesInitialStmt, updateSeriesInitial, arg.NameInitial, arg.ID)
	return err
}

const updateSeriesMetadata = `-- name: UpdateSeriesMetadata :one
UPDATE series
SET 
    title = ?,
    summary = ?,
    publisher = ?,
    status = ?,
    rating = ?,
    language = ?,
    locked_fields = ?,
    name_initial = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, library_id, name, title, summary, publisher, status, rating, language, locked_fields, name_initial, path, created_at, updated_at, is_favorite, volume_count, book_count, total_pages
`

type UpdateSeriesMetadataParams struct {
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	NameInitial  string          `json:"name_initial"`
	ID           int64           `json:"id"`
}

func (q *Queries) UpdateSeriesMetadata(ctx context.Context, arg UpdateSeriesMetadataParams) (Series, error) {
	row := q.queryRow(ctx, q.updateSeriesMetadataStmt, updateSeriesMetadata,
		arg.Title,
		arg.Summary,
		arg.Publisher,
		arg.Status,
		arg.Rating,
		arg.Language,
		arg.LockedFields,
		arg.NameInitial,
		arg.ID,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Title,
		&i.Summary,
		&i.Publisher,
		&i.Status,
		&i.Rating,
		&i.Language,
		&i.LockedFields,
		&i.NameInitial,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsFavorite,
		&i.VolumeCount,
		&i.BookCount,
		&i.TotalPages,
	)
	return i, err
}

const updateSeriesStatistics = `-- name: UpdateSeriesStatistics :exec
UPDATE series
SET 
    volume_count = (SELECT COUNT(DISTINCT NULLIF(b.volume, '')) FROM books b WHERE b.series_id = ?),
    book_count = (SELECT COUNT(*) FROM books b WHERE b.series_id = ?),
    total_pages = (SELECT COALESCE(SUM(page_count), 0) FROM books b WHERE b.series_id = ?),
    updated_at = CURRENT_TIMESTAMP
WHERE series.id = ?
`

type UpdateSeriesStatisticsParams struct {
	SeriesID   int64 `json:"series_id"`
	SeriesID_2 int64 `json:"series_id_2"`
	SeriesID_3 int64 `json:"series_id_3"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateSeriesStatistics(ctx context.Context, arg UpdateSeriesStatisticsParams) error {
	_, err := q.exec(ctx, q.updateSeriesStatisticsStmt, updateSeriesStatistics,
		arg.SeriesID,
		arg.SeriesID_2,
		arg.SeriesID_3,
		arg.ID,
	)
	return err
}

const upsertAuthor = `-- name: UpsertAuthor :one
INSERT INTO authors (name, role) VALUES (?, ?)
ON CONFLICT(name, role) DO UPDATE SET name = excluded.name, role=excluded.role
RETURNING id, name, role, created_at
`

type UpsertAuthorParams struct {
	Name string `json:"name"`
	Role string `json:"role"`
}

func (q *Queries) UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) (Author, error) {
	row := q.queryRow(ctx, q.upsertAuthorStmt, upsertAuthor, arg.Name, arg.Role)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const upsertBookByPath = `-- name: UpsertBookByPath :one
INSERT INTO books (
    series_id, library_id, name, path, size, file_modified_at, 
    volume, title, summary, number, sort_number, page_count, cover_path
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(path) DO UPDATE SET
    series_id = excluded.series_id,
    library_id = excluded.library_id,
    name = excluded.name,
    size = excluded.size,
    file_modified_at = excluded.file_modified_at,
    volume = excluded.volume,
    title = excluded.title,
    summary = excluded.summary,
    number = excluded.number,
    sort_number = excluded.sort_number,
    page_count = excluded.page_count,
    cover_path = excluded.cover_path,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, series_id, library_id, name, path, size, file_modified_at, volume, title, summary, number, sort_number, page_count, cover_path, last_read_page, last_read_at, file_hash, quick_hash, path_fingerprint, path_fingerprint_no_ext, filename_fingerprint, created_at, updated_at
`

type UpsertBookByPathParams struct {
	SeriesID       int64           `json:"series_id"`
	LibraryID      int64           `json:"library_id"`
	Name           string          `json:"name"`
	Path           string          `json:"path"`
	Size           int64           `json:"size"`
	FileModifiedAt time.Time       `json:"file_modified_at"`
	Volume         string          `json:"volume"`
	Title          sql.NullString  `json:"title"`
	Summary        sql.NullString  `json:"summary"`
	Number         sql.NullString  `json:"number"`
	SortNumber     sql.NullFloat64 `json:"sort_number"`
	PageCount      int64           `json:"page_count"`
	CoverPath      sql.NullString  `json:"cover_path"`
}

func (q *Queries) UpsertBookByPath(ctx context.Context, arg UpsertBookByPathParams) (Book, error) {
	row := q.queryRow(ctx, q.upsertBookByPathStmt, upsertBookByPath,
		arg.SeriesID,
		arg.LibraryID,
		arg.Name,
		arg.Path,
		arg.Size,
		arg.FileModifiedAt,
		arg.Volume,
		arg.Title,
		arg.Summary,
		arg.Number,
		arg.SortNumber,
		arg.PageCount,
		arg.CoverPath,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.LibraryID,
		&i.Name,
		&i.Path,
		&i.Size,
		&i.FileModifiedAt,
		&i.Volume,
		&i.Title,
		&i.Summary,
		&i.Number,
		&i.SortNumber,
		&i.PageCount,
		&i.CoverPath,
		&i.LastReadPage,
		&i.LastReadAt,
		&i.FileHash,
		&i.QuickHash,
		&i.PathFingerprint,
		&i.PathFingerprintNoExt,
		&i.FilenameFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSeriesByPath = `-- name: UpsertSeriesByPath :one
INSERT INTO series (
    library_id, name, path, title, summary, publisher, status, rating, language, locked_fields, is_favorite,
    volume_count, book_count, total_pages, name_initial
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(path) DO UPDATE SET
    library_id = excluded.library_id,
    name = excluded.name,
    name_initial = excluded.name_initial,
    title = excluded.title,
    summary = excluded.summary,
    publisher = excluded.publisher,
    status = excluded.status,
    rating = excluded.rating,
    language = excluded.language,
    locked_fields = excluded.locked_fields,
    volume_count = excluded.volume_count,
    book_count = excluded.book_count,
    total_pages = excluded.total_pages,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, library_id, name, title, summary, publisher, status, rating, language, locked_fields, name_initial, path, created_at, updated_at, is_favorite, volume_count, book_count, total_pages
`

type UpsertSeriesByPathParams struct {
	LibraryID    int64           `json:"library_id"`
	Name         string          `json:"name"`
	Path         string          `json:"path"`
	Title        sql.NullString  `json:"title"`
	Summary      sql.NullString  `json:"summary"`
	Publisher    sql.NullString  `json:"publisher"`
	Status       sql.NullString  `json:"status"`
	Rating       sql.NullFloat64 `json:"rating"`
	Language     sql.NullString  `json:"language"`
	LockedFields sql.NullString  `json:"locked_fields"`
	IsFavorite   bool            `json:"is_favorite"`
	VolumeCount  int64           `json:"volume_count"`
	BookCount    int64           `json:"book_count"`
	TotalPages   int64           `json:"total_pages"`
	NameInitial  string          `json:"name_initial"`
}

func (q *Queries) UpsertSeriesByPath(ctx context.Context, arg UpsertSeriesByPathParams) (Series, error) {
	row := q.queryRow(ctx, q.upsertSeriesByPathStmt, upsertSeriesByPath,
		arg.LibraryID,
		arg.Name,
		arg.Path,
		arg.Title,
		arg.Summary,
		arg.Publisher,
		arg.Status,
		arg.Rating,
		arg.Language,
		arg.LockedFields,
		arg.IsFavorite,
		arg.VolumeCount,
		arg.BookCount,
		arg.TotalPages,
		arg.NameInitial,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Title,
		&i.Summary,
		&i.Publisher,
		&i.Status,
		&i.Rating,
		&i.Language,
		&i.LockedFields,
		&i.NameInitial,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsFavorite,
		&i.VolumeCount,
		&i.BookCount,
		&i.TotalPages,
	)
	return i, err
}

const upsertSeriesMetadataProvenance = `-- name: UpsertSeriesMetadataProvenance :one
INSERT INTO series_metadata_provenance (
    series_id, field_name, value, source, source_url, confidence, review_id
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7
)
ON CONFLICT(series_id, field_name) DO UPDATE SET
    value = excluded.value,
    source = excluded.source,
    source_url = excluded.source_url,
    confidence = excluded.confidence,
    review_id = excluded.review_id,
    updated_at = CURRENT_TIMESTAMP
RETURNING series_id, field_name, value, source, source_url, confidence, review_id, updated_at
`

type UpsertSeriesMetadataProvenanceParams struct {
	SeriesID   int64         `json:"series_id"`
	FieldName  string        `json:"field_name"`
	Value      string        `json:"value"`
	Source     string        `json:"source"`
	SourceUrl  string        `json:"source_url"`
	Confidence float64       `json:"confidence"`
	ReviewID   sql.NullInt64 `json:"review_id"`
}

func (q *Queries) UpsertSeriesMetadataProvenance(ctx context.Context, arg UpsertSeriesMetadataProvenanceParams) (SeriesMetadataProvenance, error) {
	row := q.queryRow(ctx, q.upsertSeriesMetadataProvenanceStmt, upsertSeriesMetadataProvenance,
		arg.SeriesID,
		arg.FieldName,
		arg.Value,
		arg.Source,
		arg.SourceUrl,
		arg.Confidence,
		arg.ReviewID,
	)
	var i SeriesMetadataProvenance
	err := row.Scan(
		&i.SeriesID,
		&i.FieldName,
		&i.Value,
		&i.Source,
		&i.SourceUrl,
		&i.Confidence,
		&i.ReviewID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = excluded.name
RETURNING id, name, created_at
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.queryRow(ctx, q.upsertTagStmt, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
